export const styles = {
  modalContent: {
    padding: '$0' as const,
    borderRadius: '$2xl' as const,
    overflow: 'hidden' as const,
    bg: '$white' as const,
  },
  modalContainer: {
    width: '$full' as const,
    bg: '$white' as const,
    borderRadius: '$2xl' as const,
    p: '$3' as const,
    alignItems: 'center' as const,
    position: 'relative' as const,
  },
  contentWrapper: {
    space: 'xs' as const,
    alignItems: 'center' as const,
    width: '$full' as const,
  },
  closeButton: {
    position: 'absolute' as const,
    top: -8,
    right: -3,
    zIndex: 10,
    padding: 6,
    borderRadius: '$full' as const,
  },
  iconWrapper: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#f6cddd' as const,
    bg: '#FDF2F4' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: '$3' as const,
  },
  smartphoneIconColor: '$primary500',
  badgeReady: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    bg: '#ECFDF5' as const,
    borderWidth: 1,
    borderColor: '#A7F3D0' as const,
    borderRadius: '$full' as const,
    paddingHorizontal: '$3' as const,
    paddingVertical: '$1' as const,
    marginBottom: '$2.5' as const,
  },
  badgeReadyIconColor: '$green600',
  badgeReadyText: {
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
    color: '#059669' as const,
    marginLeft: '$1' as const,
  },
  badgeUnconfigured: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    bg: '#FFFBEB' as const,
    borderWidth: 1,
    borderColor: '#FDE68A' as const,
    borderRadius: '$full' as const,
    paddingHorizontal: '$3' as const,
    paddingVertical: '$1' as const,
    marginBottom: '$2.5' as const,
  },
  badgeUnconfiguredIconColor: '$amber600',
  badgeUnconfiguredText: {
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
    color: '#D97706' as const,
    marginLeft: '$1' as const,
  },
  appName: {
    fontSize: '$lg' as const,
    fontWeight: '$bold' as const,
    textAlign: 'center' as const,
    color: '$textDark900' as const,
    marginBottom: '$1.5' as const,
  },
  description: {
    fontSize: '$sm' as const,
    textAlign: 'center' as const,
    color: '$textSecondary' as const,
    marginBottom: '$4' as const,
    maxWidth: 370,
    lineHeight: 18,
  },
  downloadButton: {
    bg: '$primary500' as const,
    width: '$full' as const,
    borderRadius: '$xl' as const,
    marginBottom: '$3' as const,
  },
  downloadButtonIconColor: '$white',
  downloadButtonText: {
    color: '$white' as const,
    fontWeight: '$bold' as const,
    fontSize: '$sm' as const,
    marginLeft: '$1.5' as const,
  },
  guideToggle: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: '$1.5' as const,
  },
  guideToggleIconColor: '$textMuted' as const,
  guideToggleText: {
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
    color: '$textDark' as const,
    marginHorizontal: '$1.5' as const,
  },
  guideBox: {
    width: '$full' as const,
    bg: '#F8FAFC' as const,
    borderWidth: 1,
    borderColor: '#E2E8F0' as const,
    borderRadius: '$xl' as const,
    padding: '$3.5' as const,
  },
  guideStep: {
    marginBottom: '$1' as const,
  },
  guideStepLast: {
    marginBottom: '$0' as const,
  },
  guideStepTitle: {
    fontSize: '$xs' as const,
    fontWeight: '$bold' as const,
    color: '#334155' as const,
  },
  guideStepDesc: {
    fontSize: '$xs' as const,
    color: '#64748B' as const,
  },
  noticeBox: {
    width: '$full' as const,
    bg: '#FFFBEB' as const,
    borderWidth: 1,
    borderColor: '#FCD34D' as const,
    borderRadius: '$xl' as const,
    padding: '$3' as const,
    marginBottom: '$4' as const,
  },
  noticeBoxIconColor: '$amber700',
  noticeTitle: {
    fontSize: '$xs' as const,
    fontWeight: '$bold' as const,
    color: '#B45309' as const,
  },
  noticeText: {
    fontSize: '$xs' as const,
    color: '#B45309' as const,
    flexShrink: 1,
    marginLeft: '$1' as const,
  },
  continueButton: {
    borderColor: '#CBD5E1' as const,
    bg: '$white' as const,
    width: '$full' as const,
    borderRadius: '$xl' as const,
  },
  continueButtonText: {
    color: '#1E293B' as const,
    fontWeight: '$bold' as const,
    fontSize: '$sm' as const,
  },
} as const;
