export const outcomesStyles = {
  participantSelector: {
    w: '$full' as const,
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderColor' as const,
    borderRadius: 16,
    p: 20,
  },
  participantStatusCard: {
    w: '$full' as const,
  },
  cardsContainer: {
    space: 'md' as const,
    w: '$full',
  },
  selectorRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
    flexWrap: 'wrap' as const,
  },
  titletextselector: {
    fontSize: '$sm' as const,
    fontWeight: '$medium' as const,
    color: '$textSecondary' as const,
    pr: 10,
  },
  selectTrigger: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: '$lg',
    px: '$3',
    py: '$2',
    bg: '$white',
    minWidth: 260,
  },
  dropdownOverlay: {
    position: 'absolute' as const,
    top: 42,
    left: 0,
    right: 0,
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: '$lg',
    zIndex: 1000,
    shadowColor: '$shadowColor',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  dropdownSearchInputContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    borderWidth: 1,
    borderColor: '$borderLight200',
    bg: '$backgroundLight50',
    borderRadius: '$md',
    px: '$3',
    h: 36,
    m: '$2',
  },
  dropdownSearchInputField: {
    flex: 1,
    fontSize: '$sm',
    fontFamily: 'Inter',
    color: '$textPrimary',
    padding: 0,
    marginLeft: 8,
  },
  dropdownList: {
    maxHeight: 220,
  },
  dropdownItem: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    px: '$3',
    py: '$2.5',
    borderBottomWidth: 1,
    borderColor: '$backgroundLight100',
  },
  dropdownItemHovered: {
    bg: '$backgroundLight100',
  },
  emptyStateContainer: {
    bg: '$white',
    borderRadius: 16,
    p: 20,
    borderWidth: 1,
    borderColor: '$borderColor',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    space: 'md' as const,
    mt: '$2' as const,
  },
  emptyStateText: {
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
    color: '$textMuted' as const,
  },
  statusGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: '$3' as const,
  },
  statusItem: {
    width: '100%' as const,
    p: 20,
    bg: '$white',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '$borderColor',
    justifyContent: 'space-between' as const,
    minHeight: 94,
    $md: {
      width: '23.5%' as const,
    },
  },
  statusItemHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'xs' as const,
    mb: '$4' as const,
  },
  statusItemValueRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
  },
  statusItemSubLabelRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'xs' as const,
    mt: '$1' as const,
  },
  // Card base & inner layout
  cardRow: {
    flexDirection: 'column' as const,
    gap: '$3' as const,
    w: '$full',
    $md: {
      flexDirection: 'row' as const,
    },
  },
  profitabilityCard: {
    w: '$full' as const,
    mt: '$3' as const,
  },
  incomeSavingsCard: {
    w: '$full' as const,
  },
  incomeSelfEfficacyCard: {
    w: '$full' as const,
  },
  profitabilityAgencyCard: {
    w: '$full' as const,
  },
  // Inner boxes
  incomeTrendBox: {
    flex: 1,
    p: '$5',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 16,
    bg: '$white',
  },
  savingsTrendBox: {
    flex: 1,
    p: '$5',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 16,
    bg: '$white',
  },
  incomeSourcesBox: {
    flex: 1,
    p: '$5',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 16,
    bg: '$white',
  },
  selfEfficacyBox: {
    flex: 1,
    p: '$5',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 16,
    bg: '$white',
  },
  profitabilityBox: {
    flex: 1,
    p: '$5',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 16,
    bg: '$white',
  },
  agencyBox: {
    flex: 1,
    p: '$5',
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: 16,
    bg: '$white',
  },
  // Charts & components inside boxes
  chartContainer: {
    height: 320,
    w: '$full',
    mt: '$2' as const,
  },
  sourceRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
  },
  sourceProgressBarContainer: {
    space: 'xs' as const,
    mb: '$3' as const,
  },
  agencyContentCard: {
    flex: 1,
    bg: '$success50',
    borderColor: '$success200',
    borderWidth: 1,
    borderRadius: '$lg',
    p: '$5',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    space: 'xs' as const,
    minHeight: 320,
    mt: '$2' as const,
  },
  agencyIconContainer: {
    bg: '$success100',
    p: '$2',
    borderRadius: '$full',
    mb: '$2' as const,
  },
  metricTitle: {
    fontSize: '$md !important',
    fontWeight: 'normal' as const,
    color: '$black' as const,
  },
  metricTitle1: {
    fontSize: '$xs !important',
    fontWeight: 'normal' as const,
    color: '$black' as const,
  },
  metricValue: {
    fontSize: '$md !important',
    fontWeight: 'normal' as const,
    color: '$textPrimary' as const,
    marginBottom: 2,
  },
  metricSubtext: {
    fontSize: '$sm !important',
    fontWeight: 'normal' as const,
  },
  metricsubtitle1: {
    fontSize: '$xs !important',
    fontWeight: 'normal' as const,
    color: '$textMutedForeground' as const,
  },
} as const;
