export const requestDetailsStyles = {
  detailsScreenRoot: {
    flex: 1,
    bg: '#F8FAFC',
  },
  detailsHeaderBackButton: {
    color: '$textPrimary',
  },
  detailsHeaderTitle: {
    fontSize: '$xl',
    fontWeight: '$bold',
    color: '$textPrimary',
  },
  detailsHeaderSubtitle: {
    fontSize: '$xs',
    color: '$textSecondary',
    mt: '$0.5',
  },
  detailsMainContainer: {
    flex: 1,
    py: '$6',
    px: '$4',
  },
  detailsLayoutWrapper: {
    space: 'lg' as const,
    width: '100%',
  },
  detailsCard: {
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: 24,
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
    width: '100%',
    mb: '$5',
    overflow: 'hidden' as const,
  },
  detailsCardBanner: {
    bg: '#F8FAFC',
    borderBottomWidth: 1,
    borderColor: '$borderLight200',
    px: '$6',
    py: '$4',
    width: '100%',
  },
  detailsCardContent: {
    px: '$6',
    py: '$6',
    width: '100%',
  },
  statusHeaderRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%',
  },
  statusLabelText: {
    fontSize: '$xs',
    fontWeight: '$semibold' as const,
    color: '$textMuted',
    letterSpacing: '$md',
  },
  requestedOnText: {
    fontSize: '$sm',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
    mt: '$1',
  },
  statusBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    alignSelf: 'flex-start' as const,
    borderWidth: 1,
    borderRadius: '$full' as const,
    px: '$2.5',
    py: '$0.5',
    gap: '$1',
    mt: '$1.5',
  },
  statusBadgeText: {
    fontSize: '$xs',
    fontWeight: '$normal' as const,
    textTransform: 'none' as const,
  },
  metaGridRow: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: '$6',
    mb: '$5',
    width: '100%',
  },
  metaItem: {
    flex: 1,
    minWidth: 150,
    space: 'xs' as const,
  },
  metaLabel: {
    fontSize: '$xs',
    color: '$textMuted',
    fontWeight: '$semibold' as const,
    mb: '$1',
  },
  metaValue: {
    fontSize: '$sm',
    fontWeight: '$semibold' as const,
    color: '$textPrimary',
  },
  titleText: {
    fontSize: '$md',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
  },
  notesHeader: {
    fontSize: '$xs',
    fontWeight: '$semibold' as const,
    color: '$textMuted',
    mb: '$2',
  },
  notesBox: {
    bg: '#F8FAFC',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: '$lg' as const,
    px: '$4',
    py: '$3',
    width: '100%',
  },
  notesText: {
    fontSize: '$sm',
    color: '$textSecondary',
    lineHeight: '$md',
  },
  infoCardHeader: {
    fontSize: '$md',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
  },
  infoRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    py: '$3',
    width: '100%',
  },
  infoRowLast: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    py: '$3',
    width: '100%',
  },
  infoRowLabel: {
    width: '35%',
    fontSize: '$sm',
    color: '$textMuted',
    fontWeight: '$normal' as const,
  },
  infoRowValue: {
    width: '65%',
    fontSize: '$sm',
    color: '$textPrimary',
    fontWeight: '$normal' as const,
  },
} as const;

export default requestDetailsStyles;
