export const dashboardHeaderStyles = {
  container: {
    mb: 0 as const,
  },
  filterBoxWrapper: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderColor' as const,
    borderRadius: '$xl' as const,
    width: '$full' as const,
    padding: 8,
    columnGap: 8,
    rowGap: 8,
    height: 52,
    marginBottom: 20,
    shadowColor: '$shadowColor',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    '$web-boxShadow': '0px 1px 3px rgba(0, 0, 0, 0.1)' as const,
  },
  filterIcon: {
    color: '$primary500' as const,
    size: 13,
    ml: 8,
  },
  filterButtonOverride: {
    mt: 0,
    p: '$0 !important',
    borderWidth: 0,
    bg: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
    width: 'auto',
    flex: 1,
  },
  filterInputOverride: {
    height: 36,
    borderRadius: '$md' as const,
    bg: '$white' as const,
    borderColor: '$borderColor' as const,
    width: '140 !important',
    paddingTop: '$sm !important',
    paddingBottom: '$sm !important',
    paddingLeft: '$md !important',
    paddingRight: '$md !important',
  },
  tabsContainer: {
    bg: '$accent200' as const,
    borderRadius: 16,
    padding: 3,
    height: 36,
    width: 672,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    alignSelf: 'flex-start' as const,
    borderWidth: 0,
    mb: '$1 !important',
  },
  tabButton: (isActive: boolean) => ({
    flex: 1 as const,
    bg: isActive ? '$white' : 'transparent',
    borderRadius: 13,
    paddingTop: isActive ? 8 : undefined,
    paddingBottom: isActive ? 8 : undefined,
    paddingLeft: isActive ? 4 : undefined,
    paddingRight: isActive ? 4 : undefined,
    px: isActive ? undefined : '$4',
    height: 30,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    elevation: isActive ? 1 : 0,
    shadowColor: isActive ? '$shadowColor' : 'transparent',
    shadowOffset: isActive ? { width: 0, height: 1 } : { width: 0, height: 0 },
    shadowOpacity: isActive ? 0.1 : 0,
    shadowRadius: isActive ? 1 : 0,
  }),
  tabText: (isActive: boolean) => ({
    fontSize: 14,
    fontWeight: '500' as const,
    color: isActive ? '$textForeground' : '$textMutedForeground',
  }),
} as const;
