export const userManagementStyles = {
  scrollView: {
    flex: 1,
    width: '100%',
    p: '$4',
    bg: '$backgroundLight0',
  },
  statsHStack: {
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  sectionsContainer: {
    flexWrap: 'wrap',
    space: 'lg',
  },
  sectionBox: {
    flex: 1,
    w: '100%',
  },
  sectionTitle: {
    fontWeight: '$bold',
    mb: '$2',
  },
  // Quick Actions Card
  quickActionsCard: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    rounded: '$2xl',
    p: '$4',
    bg: '$backgroundLight0',
  },
  // Upload Users Modal Card Styles
  uploadOptionCard: {
    borderRadius: '$lg',
    borderWidth: 1,
    borderColor: '$borderLight200',
    padding: '$4',
    '$web-cursor': 'pointer' as const,
    '$web-transition': 'background-color 0.2s ease-in-out' as const,
    '$web-boxShadow': 'none' as const,
    elevation: 0,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  uploadOptionCardDisabled: {
    borderRadius: '$lg',
    borderWidth: 1,
    borderColor: '$borderLight200',
    padding: '$4',
    opacity: 0.5,
    '$web-boxShadow': 'none' as const,
    elevation: 0,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  uploadCSVIconContainer: {
    bg: '$primary300',
    borderRadius: '$lg',
    width: 40,
    height: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  addUserIconContainer: {
    bg: '$gray100',
    borderRadius: '$lg',
    width: 40,
    height: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
} as const;
