export const PARTICIPANT_JOURNEY_CARDS = [
  {
    id: 'idp-progress',
    variant: 'link',
    icon: 'BookOpen',
    iconBg: '$blue100',
    iconColor: '$blue600',
    hoverBorderColor: '$blue600',
    hoverBg: '$blue50',
    title: 'participantJourney.cards.idpProgress',
    description: 'participantJourney.cards.idpProgressDescription',
    navigationUrl: 'idp-progress',
  },
  {
    id: 'sessions',
    variant: 'link',
    icon: 'Calendar',
    iconBg: '$purple100',
    iconColor: '$purple600',
    hoverBorderColor: '$purple600',
    hoverBg: '$purple50',
    title: 'participantJourney.cards.sessions',
    description: 'participantJourney.cards.sessionsDescription',
    navigationUrl: 'my-sessions',
  },
  {
    id: 'graduation',
    variant: 'link',
    icon: 'Award',
    iconBg: '$success100',
    iconColor: '$success600',
    hoverBorderColor: '$success600',
    hoverBg: '$success50',
    title: 'participantJourney.cards.graduation',
    description: 'participantJourney.cards.graduationDescription',
    navigationUrl: 'my-graduation',
  },
  {
    id: 'coach-details',
    variant: 'coach',
    rows: [
      {
        id: 'coach-name',
        icon: 'User',
        iconBg: '$orange50',
        iconColor: '$orange500',
        label: 'participantJourney.cards.coachName',
      },
      {
        id: 'coach-contact',
        icon: 'Phone',
        iconBg: '$success50',
        iconColor: '$success600',
        label: 'participantJourney.cards.contact',
      },
    ],
  },
];
