import type { UnifiedParticipant, Province, Site } from '@app-types/participant';

/**
 * South African Provinces
 * Mock data for province selection dropdown
 * TODO: Replace with API call in future
 */

export const PROVINCES: Province[] = [
  { value: 'eastern-cape', label: 'Eastern Cape' },
  { value: 'free-state', label: 'Free State' },
  { value: 'gauteng', label: 'Gauteng' },
  { value: 'kwazulu-natal', label: 'KwaZulu-Natal' },
  { value: 'limpopo', label: 'Limpopo' },
  { value: 'mpumalanga', label: 'Mpumalanga' },
  { value: 'northern-cape', label: 'Northern Cape' },
  { value: 'north-west', label: 'North West' },
  { value: 'western-cape', label: 'Western Cape' },
] as const;

/**
 * Site Options
 * Mock data for site selection dropdown
 * TODO: Replace with API call in future (may depend on selected province)
 */
export const SITES: Site[] = [
  { value: 'site-a', label: 'Site A - Urban', type: 'Urban' },
  { value: 'site-b', label: 'Site B - Urban', type: 'Urban' },
  { value: 'site-c', label: 'Site C - Rural', type: 'Rural' },
  { value: 'site-d', label: 'Site D - Rural', type: 'Rural' },
  { value: 'site-e', label: 'Site E - Peri-urban', type: 'Peri-urban' },
  { value: 'site-f', label: 'Site F - Peri-urban', type: 'Peri-urban' },
] as const;

/**
 * Mock Participants Data
 * Single source of truth for all participant data
 * Used for demo purposes until API is integrated
 */
export const PARTICIPANTS_DATA: UnifiedParticipant[] = [
  {
    id: 'P-006',
    name: 'Aisha Patel',
    progress: 0,
    email: 'aisha@example.com',
    phone: '(555) 678-9012',
    address: '123 Main Street, City, State',
    status: 'not_enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-009',
    name: 'David Freeman',
    progress: 0,
    email: 'david@example.com',
    phone: '(555) 901-2345',
    address: '456 Oak Avenue, City, State',
    status: 'enrolled',
    pathway: 'employment',
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-014',
    name: 'Natasha Ivanova',
    progress: 57,
    email: 'natasha@example.com',
    phone: '(555) 456-7890',
    address: '789 Pine Road, City, State',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 57,
    graduationDate: undefined,
  },
  {
    id: 'P-019',
    name: 'Tyler Mitchell',
    progress: 100,
    email: 'tyler@example.com',
    phone: '(555) 901-2345',
    address: '321 Elm Street, City, State',
    status: 'completed',
    pathway: 'entrepreneurship',
    graduationProgress: 100,
    graduationDate: '2025-09-20',
  },
  {
    id: 'P-020',
    name: 'John Doe',
    progress: 10,
    email: 'john@example.com',
    phone: '(555) 901-2345',
    address: '654 Maple Drive, City, State',
    status: 'dropout',
    pathway: 'entrepreneurship',
    graduationProgress: 50,
    graduationDate: undefined,
  },
  {
    id: 'P-1002',
    name: 'Khanyi Ndlovu',
    progress: 0,
    email: 'khanyi.ndlovu@example.com',
    phone: '073 456 7890',
    address: '',
    status: 'not_enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-1006',
    name: 'Lindiwe Radebe',
    progress: 0,
    email: 'lindiwe.radebe@example.com',
    phone: '077 678 9012',
    address: '',
    status: 'not_enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-1014',
    name: 'Busisiwe Shabalala',
    progress: 0,
    email: 'busisiwe.shabalala@example.com',
    phone: '088 456 7890',
    address: '',
    status: 'not_enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-1019',
    name: 'David Chen',
    progress: 0,
    email: 'david.chen@example.com',
    phone: '(555) 901-2345',
    address: '',
    status: 'not_enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-1006A',
    name: 'Zinhle Bhengu',
    progress: 0,
    email: 'zinhle.bhengu@example.com',
    phone: '077 678 9013',
    address: '',
    status: 'enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-1006B',
    name: 'Thandiwe Ngubane',
    progress: 0,
    email: 'thandiwe.ngubane@example.com',
    phone: '077 678 9014',
    address: '',
    status: 'enrolled',
    pathway: undefined,
    graduationProgress: undefined,
    graduationDate: undefined,
  },
  {
    id: 'P-1001',
    name: 'Thabiso Dlamini',
    progress: 68,
    email: 'thabiso.dlamini@example.com',
    phone: '072 345 6789',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 68,
    graduationDate: undefined,
  },
  {
    id: 'P-1004',
    name: 'Nosipho Khumalo',
    progress: 82,
    email: 'nosipho.khumalo@example.com',
    phone: '074 456 7890',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 82,
    graduationDate: undefined,
  },
  {
    id: 'P-1005',
    name: 'Sizwe Mkhize',
    progress: 45,
    email: 'sizwe.mkhize@example.com',
    phone: '076 567 8901',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 45,
    graduationDate: undefined,
  },
  {
    id: 'P-1006C',
    name: 'Bongani Zungu',
    progress: 5,
    email: 'bongani.zungu@example.com',
    phone: '077 678 9015',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 5,
    graduationDate: undefined,
  },
  {
    id: 'P-1006D',
    name: 'Mbali Cele',
    progress: 8,
    email: 'mbali.cele@example.com',
    phone: '077 678 9016',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 8,
    graduationDate: undefined,
  },
  {
    id: 'P-1007',
    name: 'Andile Nkosi',
    progress: 28,
    email: 'andile.nkosi@example.com',
    phone: '078 789 0123',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 28,
    graduationDate: undefined,
  },
  {
    id: 'P-1008',
    name: 'Keke Mahlangu',
    progress: 91,
    email: 'keke.mahlangu@example.com',
    phone: '079 890 1234',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 91,
    graduationDate: undefined,
  },
  {
    id: 'P-1010',
    name: 'Dakalo Ramaano',
    progress: 15,
    email: 'dakalo.ramaano@example.com',
    phone: '083 012 3456',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 15,
    graduationDate: undefined,
  },
  {
    id: 'P-1012',
    name: 'Khathu Mudau',
    progress: 58,
    email: 'khathu.mudau@example.com',
    phone: '085 234 5678',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 58,
    graduationDate: undefined,
  },
  {
    id: 'P-1013',
    name: 'Lufuno Ramavhoya',
    progress: 34,
    email: 'lufuno.ramavhoya@example.com',
    phone: '087 345 6789',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 34,
    graduationDate: undefined,
  },
  {
    id: 'P-1015',
    name: 'Jamal Harris',
    progress: 73,
    email: 'jamal.harris@example.com',
    phone: '(555) 567-8901',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 73,
    graduationDate: undefined,
  },
  {
    id: 'P-1016',
    name: 'Rebecca Stone',
    progress: 19,
    email: 'rebecca.stone@example.com',
    phone: '(555) 678-9012',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 19,
    graduationDate: undefined,
  },
  {
    id: 'P-1018',
    name: 'Monica Rivera',
    progress: 51,
    email: 'monica.rivera@example.com',
    phone: '(555) 890-1234',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 51,
    graduationDate: undefined,
  },
  {
    id: 'P-1020',
    name: 'Angela Cooper',
    progress: 64,
    email: 'angela.cooper@example.com',
    phone: '(555) 012-3456',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 64,
    graduationDate: undefined,
  },
  {
    id: 'P-1021',
    name: 'Brandon Lee',
    progress: 87,
    email: 'brandon.lee@example.com',
    phone: '(555) 123-4567',
    address: '',
    status: 'in_progress',
    pathway: 'employment',
    graduationProgress: 87,
    graduationDate: undefined,
  },
  {
    id: 'P-1006E',
    name: 'Sipho Dube',
    progress: 100,
    email: 'sipho.dube@example.com',
    phone: '077 678 9017',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-10-15',
  },
  {
    id: 'P-1006F',
    name: 'Nomvula Zulu',
    progress: 100,
    email: 'nomvula.zulu@example.com',
    phone: '077 678 9018',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-10-20',
  },
  {
    id: 'P-1011',
    name: 'Kabelo Moeti',
    progress: 100,
    email: 'kabelo.moeti@example.com',
    phone: '084 123 4567',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-10-25',
  },
  {
    id: 'P-1017',
    name: 'Ahmed Hassan',
    progress: 100,
    email: 'ahmed.hassan@example.com',
    phone: '(555) 789-0123',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-11-01',
  },
  {
    id: 'P-024',
    name: 'Daniel Kowalski',
    progress: 100,
    email: 'daniel.kowalski@example.com',
    phone: '(555) 456-7890',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-11-05',
  },
  {
    id: 'P-025',
    name: 'Tamika Jefferson',
    progress: 100,
    email: 'tamika.jefferson@example.com',
    phone: '(555) 567-8901',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-11-10',
  },
  {
    id: 'P-026',
    name: 'Victor Santos',
    progress: 100,
    email: 'victor.santos@example.com',
    phone: '(555) 678-9012',
    address: '',
    status: 'completed',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-11-15',
  },
  {
    id: 'P-027',
    name: 'Zanele Sithole',
    progress: 100,
    email: 'zanele.sithole@example.com',
    phone: '078 123 4567',
    address: '',
    status: 'graduated',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-12-01',
  },
  {
    id: 'P-028',
    name: 'Bongani Mthembu',
    progress: 100,
    email: 'bongani.mthembu@example.com',
    phone: '079 234 5678',
    address: '',
    status: 'graduated',
    pathway: 'entrepreneurship',
    graduationProgress: 100,
    graduationDate: '2025-12-05',
  },
  {
    id: 'P-029',
    name: 'Precious Nkosi',
    progress: 100,
    email: 'precious.nkosi@example.com',
    phone: '080 345 6789',
    address: '',
    status: 'graduated',
    pathway: 'employment',
    graduationProgress: 100,
    graduationDate: '2025-12-10',
  },
  {
    id: 'P-030',
    name: 'Andile Zuma',
    progress: 100,
    email: 'andile.zuma@example.com',
    phone: '081 456 7890',
    address: '',
    status: 'graduated',
    pathway: 'entrepreneurship',
    graduationProgress: 100,
    graduationDate: '2025-12-15',
  },
];
