import { ProjectData } from '../project-player/types/project.types';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { STORAGE_KEYS } from './STORAGE_KEYS';

declare const process:
  | {
      env: {
        [key: string]: string | undefined;
      };
    }
  | undefined;

const baseUrl = process.env.API_BASE_URL;

// Helper function to get access token from AsyncStorage
export const getAccessToken = async (): Promise<string | null> => {
  try {
    const token = await AsyncStorage.getItem(STORAGE_KEYS.AUTH_TOKEN);
    return token;
  } catch (error) {
    console.error('Error getting token from AsyncStorage:', error);
    return null;
  }
};

export const PROJECT_PLAYER_CONFIGS = {
  maxFileSize: 50,
  baseUrl: baseUrl,
  accessToken: getAccessToken,
  language: 'en',
  profileInfo: {
    id: 123,
    name: 'John Doe',
  },
  redirectionLinks: {
    unauthorizedRedirectUrl: '/login',
  },
  data: {
    solutionId: 'solution_001',
    projectId: 'GBL_P01_ONBOARDING',
  },
};

export const MODE = {
  // Edit mode with full permissions
  editMode: {
    mode: 'edit' as const,
  },
  // Preview mode (template view)
  previewMode: {
    mode: 'preview' as const,
  },

  // Read-only mode
  readOnlyMode: {
    mode: 'read-only' as const,
  },
};

export const COMPLEX_PROJECT_DATA: ProjectData = {
  _id: 'Employment Pathway',
  solutionId: 'sol-community-health-001',
  title: 'Employment Pathway',
  description:
    'Comprehensive intervention plan for participants seeking formal employment with full support across all pillars',
  status: 'in-progress',
  progress: 58,
  createdAt: '2024-01-15T08:00:00Z',
  updatedAt: '2024-12-02T10:30:00Z',
  tasks: [
    {
      _id: 'task-001',
      name: 'Social Empowerment',
      description: '',
      type: 'project',
      status: 'to-do',
      isRequired: true,
      metaInformation: {
        minFiles: 1,
        category: 'onboarding',
      },
      children: [
        {
          _id: 'subtask-001',
          name: 'Organize & Schedule training on social empowerment sessions: Session 1 - Emotional Self Awareness',
          description:
            'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-002',
          name: 'Organize & Schedule training on social empowerment sessions: Session 2 - Self Management',
          description:
            'Coordinate with service provider to schedule and organize Self Management training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
      ],
    },
    {
      _id: 'task-002',
      name: 'Livelihoods',
      description: '',
      type: 'project',
      status: 'to-do',
      isRequired: true,
      metaInformation: {
        minFiles: 1,
        category: 'onboarding',
      },
      children: [
        {
          _id: 'subtask-003',
          name: 'Organize & Schedule training on social empowerment sessions: Session 1 - Emotional Self Awareness',
          description:
            'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-004',
          name: 'Organize & Schedule training on social empowerment sessions: Session 2 - Self Management',
          description:
            'Coordinate with service provider to schedule and organize Self Management training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
      ],
    },
    // {
    //   _id: 'task-onboard-001',
    //   name: 'Capture Consent',
    //   description: 'Upload signed consent forms',
    //   type: 'file',
    //   status: 'to-do',
    //   isRequired: true,
    //   metadata: {
    //     minFiles: 1,
    //     category: 'onboarding',
    //   },
    // },
  ],
};

export const pathwaysData = {
  message: 'Project categories fetched successfully',
  status: 200,
  result: [
    {
      _id: '693fb8fcda98e72cedd4a5fd',
      isDeleted: false,
      isVisible: true,
      status: 'active',
      icon: '',
      noOfProjects: 1,
      evidences: [],
      tenantId: 'brac',
      orgId: 'brac_gbl',
      visibleToOrganizations: ['brac_gbl'],
      deleted: false,
      externalId: 'GBL_PATH_ENT',
      name: 'Entrepreneurship Pathway',
      description:
        'Comprehensive intervention plan for participants starting or enhancing a business with full support across all pillars',
      keywords: ['Entrepreneurship', 'idp'],
      hasChildCategories: true,
      metaInformation: {
        tags: ['Entrepreneurship'],
      },
      children: [
        {
          _id: '695db0aeaa053e9b4dfbb418',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parent_id: null,
          hasChildCategories: false,
          sequenceNumber: 1,
          deleted: false,
          externalId: 'L1_SOCIAL_ENT',
          name: 'Social empowerment',
          parentId: '693fb8fcda98e72cedd4a5fd',
        },
        {
          _id: '695e062f8ff0ae30558296fe',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fb8fcda98e72cedd4a5fd',
          hasChildCategories: true,
          sequenceNumber: 3,
          deleted: false,
          externalId: 'L1_LIVELIHOOD_ENT',
          name: 'Livelihood',
        },
        {
          _id: '695e07dd094c3e3177f00f40',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fb8fcda98e72cedd4a5fd',
          hasChildCategories: false,
          sequenceNumber: 7,
          deleted: false,
          externalId: 'L1_SP_ENT',
          name: 'Social protection',
        },
        {
          _id: '695e0849094c3e3177f00f4a',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fb8fcda98e72cedd4a5fd',
          hasChildCategories: false,
          sequenceNumber: 8,
          deleted: false,
          externalId: 'L1_FI_ENT',
          name: 'Financial Inclusion',
        },
      ],
      childrenCount: 4,
    },
    {
      _id: '693fc57cda98e72cedd4a603',
      isDeleted: false,
      isVisible: true,
      status: 'active',
      icon: '',
      noOfProjects: 0,
      evidences: [],
      tenantId: 'brac',
      orgId: 'brac_gbl',
      visibleToOrganizations: ['brac_gbl'],
      deleted: false,
      externalId: 'GBL_PATH_EMP',
      name: 'Employment Pathway',
      description:
        'Comprehensive intervention plan for participants seeking formal employment with full support across all pillars',
      keywords: ['Employment', 'idp'],
      hasChildCategories: true,
      metaInformation: {
        tags: ['Employment'],
      },
      children: [
        {
          _id: '695e064d8ff0ae3055829704',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fc57cda98e72cedd4a603',
          hasChildCategories: false,
          sequenceNumber: 4,
          deleted: false,
          externalId: 'L1_LIVELIHOOD_EMP',
          name: 'Livelihood',
        },
        {
          _id: '695e06738ff0ae3055829709',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fc57cda98e72cedd4a603',
          hasChildCategories: false,
          sequenceNumber: 5,
          deleted: false,
          externalId: 'L1_FI_EMP',
          name: 'Financial Inclusion',
        },
        {
          _id: '695e06828ff0ae305582970e',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fc57cda98e72cedd4a603',
          hasChildCategories: false,
          sequenceNumber: 6,
          deleted: false,
          externalId: 'L1_SP_EMP',
          name: 'Social protection',
        },
        {
          _id: '695e08c5094c3e3177f00f57',
          isDeleted: false,
          isVisible: true,
          status: 'active',
          icon: '',
          noOfProjects: 0,
          evidences: [],
          tenantId: 'brac',
          orgId: 'brac_gbl',
          visibleToOrganizations: ['brac_gbl'],
          description: 'default',
          keywords: [],
          parentId: '693fc57cda98e72cedd4a603',
          hasChildCategories: false,
          sequenceNumber: 9,
          deleted: false,
          externalId: 'L1_SOCIAL_EMO',
          name: 'Social empowerment',
        },
      ],
      childrenCount: 4,
    },
  ],
};

export const templateDetailsAPIMockResponse = {
  message: 'Project categories fetched successfully',
  status: 200,
  result: {
    _id: '693fb8fcda98e72cedd4a5fd',
    createdBy: 'SYSTEM',
    updatedBy: 'SYSTEM',
    isDeleted: false,
    isVisible: true,
    status: 'active',
    icon: '',
    noOfProjects: 1,
    evidences: [],
    tenantId: 'brac',
    orgId: 'brac_gbl',
    visibleToOrganizations: ['brac_gbl'],
    deleted: false,
    externalId: 'GBL_PATH_ENT',
    name: 'Entrepreneurship Pathway',
    updatedAt: '2025-12-15T07:30:04.660Z',
    createdAt: '2025-12-15T07:30:04.660Z',
    __v: 0,
    description:
      'Comprehensive intervention plan for participants starting or enhancing a business with full support across all pillars',
    keywords: ['Entrepreneurship', 'idp'],
    hasChildCategories: true,
    children: [
      {
        _id: '695db0aeaa053e9b4dfbb418',
        icon: '',
        noOfProjects: 0,
        description: 'default',
        keywords: [],
        hasChildCategories: false,
        sequenceNumber: 1,
        externalId: 'L1_SOCIAL_ENT',
        name: 'Social empowerment',
        updatedAt: '2026-01-07T01:02:38.395Z',
        parentId: '693fb8fcda98e72cedd4a5fd',
      },
      {
        _id: '695e062f8ff0ae30558296fe',
        icon: '',
        noOfProjects: 0,
        description: 'default',
        keywords: [],
        parentId: '693fb8fcda98e72cedd4a5fd',
        hasChildCategories: true,
        sequenceNumber: 3,
        externalId: 'L1_LIVELIHOOD_ENT',
        name: 'Livelihood',
        updatedAt: '2026-01-07T07:07:27.822Z',
      },
      {
        _id: '695e07dd094c3e3177f00f40',
        icon: '',
        noOfProjects: 0,
        description: 'default',
        keywords: [],
        parentId: '693fb8fcda98e72cedd4a5fd',
        hasChildCategories: false,
        sequenceNumber: 7,
        externalId: 'L1_SP_ENT',
        name: 'Social protection',
        updatedAt: '2026-01-07T07:14:37.285Z',
      },
      {
        _id: '695e0849094c3e3177f00f4a',
        icon: '',
        noOfProjects: 0,
        description: 'default',
        keywords: [],
        parentId: '693fb8fcda98e72cedd4a5fd',
        hasChildCategories: false,
        sequenceNumber: 8,
        externalId: 'L1_FI_ENT',
        name: 'Financial Inclusion',
        updatedAt: '2026-01-07T07:16:25.199Z',
      },
    ],
  },
};

export const categoryDetailsMockData = {
  message: 'Project categories fetched successfully',
  status: 200,
  result: [
    {
      _id: '695e0a34094c3e3177f00f61',
      icon: '',
      noOfProjects: 0,
      description: 'default',
      keywords: [],
      parentId: '695e062f8ff0ae30558296fe',
      hasChildCategories: true,
      sequenceNumber: 10,
      externalId: 'L2_ENT_LIVELIHOOD_Trade',
      name: 'Trade',
      updatedAt: '2026-01-07T07:24:36.659Z',
    },
    {
      _id: '695e0a8c094c3e3177f00f74',
      icon: '',
      noOfProjects: 0,
      description: 'default',
      keywords: [],
      parentId: '695e062f8ff0ae30558296fe',
      hasChildCategories: false,
      sequenceNumber: 13,
      externalId: 'L2_ENT_LIVELIHOOD_CONSRTUCTION',
      name: 'Construction',
      updatedAt: '2026-01-07T07:26:04.494Z',
    },
    {
      _id: '695e21df9e27e03a01ff0739',
      icon: '',
      noOfProjects: 0,
      description: 'default',
      keywords: [],
      parentId: '695e062f8ff0ae30558296fe',
      hasChildCategories: false,
      sequenceNumber: 16,
      externalId: 'L2_ENT_LIVELIHOOD_CONSRTUCTION_SP',
      name: 'Service Provision',
      updatedAt: '2026-01-07T09:05:35.545Z',
    },
  ],
};

export const subCategoryDetailsMockData = {
  message: 'Project categories fetched successfully',
  status: 200,
  result: [
    {
      _id: '695e0a34094c3e3177f00f61',
      icon: '',
      noOfProjects: 0,
      description: 'default',
      keywords: [],
      parentId: '695e062f8ff0ae30558296fe',
      hasChildCategories: false,
      sequenceNumber: 10,
      externalId: 'L2_ENT_LIVELIHOOD_Trade',
      name: 'Child care',
      updatedAt: '2026-01-07T07:24:36.659Z',
    },
    {
      _id: '695e0a8c094c3e3177f00f74',
      icon: '',
      noOfProjects: 0,
      description: 'default',
      keywords: [],
      parentId: '695e062f8ff0ae30558296fe',
      hasChildCategories: false,
      sequenceNumber: 13,
      externalId: 'L2_ENT_LIVELIHOOD_CONSRTUCTION',
      name: 'Day care',
      updatedAt: '2026-01-07T07:26:04.494Z',
    },
    {
      _id: '695e21df9e27e03a01ff0739',
      icon: '',
      noOfProjects: 0,
      description: 'default',
      keywords: [],
      parentId: '695e062f8ff0ae30558296fe',
      hasChildCategories: false,
      sequenceNumber: 16,
      externalId: 'L2_ENT_LIVELIHOOD_CONSRTUCTION_SP',
      name: 'Computer repair',
      updatedAt: '2026-01-07T09:05:35.545Z',
    },
  ],
};

export const taskDetailsAPIMockResponse = {
  message: 'List of project templates fetched successfully',
  status: 200,
  result: {
    '695db0aeaa053e9b4dfbb418': [
      {
        _id: '695db0aeaa053e9b4dfbb418',
        description:
          'To Onboard a participant by taking his consent, SLA and household profile',
        concepts: [''],
        keywords: [
          'Science, Activity Based Learning, STEM Education, STEM Lab, DPDT Switch Car',
        ],
        isDeleted: false,
        recommendedFor: ['Linkage Champion'],
        tasks: [
          {
            _id: '695ef6a4479dcc69fe92b94e',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize & Schedule training on social empowerment sessions: Session 1 - Emotional Self Awareness',
            externalId: 'ONBOARD_1',
            description:
              'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
            sequenceNumber: '1',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.725Z',
            createdAt: '2026-01-08T00:13:24.725Z',
          },
          {
            _id: '695ef6a4479dcc69fe92b952',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize & Schedule training on social empowerment sessions: Session 2 - Self Management',
            externalId: 'ONBOARD_2',
            description:
              'Coordinate with service provider to schedule and organize Self Management training session for participant.',
            sequenceNumber: '2',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.750Z',
            createdAt: '2026-01-08T00:13:24.750Z',
          },
        ],
        createdBy: '3077',
        updatedBy: '3077',
        learningResources: [],
        isReusable: true,
        taskSequence: ['ONBOARD_1', 'ONBOARD_2', 'ONBOARD_3'],
        averageRating: 0,
        noOfRatings: 0,
        ratings: {
          '1': 0,
          '2': 0,
          '3': 0,
          '4': 0,
          '5': 0,
        },
        importCount: 0,
        evidences: [],
        isPrivate: false,
        hasSpotlight: false,
        hasStory: false,
        text: [],
        visibility: 'CURRENT',
        visibleToOrganizations: ['brac_gbl'],
        deleted: false,
        title: 'Social Empowerment',
        externalId: 'GBL_P01_ONBOARDING',
        categories: [
          {
            _id: '693fb8fcda98e72cedd4a5fd',
            externalId: 'GBL_PATH_ENT',
            name: 'Entrepreneurship Pathway',
          },
        ],
        entityType: 'participant',
        taskCreationForm: '',
        durationInDays: 365,
        metaInformation: {
          testimonials: [],
          goal: 'TEMP',
          rationale: '',
          primaryAudience: '',
          duration: '1 year',
          successIndicators: '',
          risks: '',
          approaches: '',
        },
        status: 'published',
        tenantId: 'brac',
        orgId: 'brac_gbl',
        updatedAt: '2025-12-17T09:44:19.355Z',
        createdAt: '2025-12-17T09:01:53.607Z',
        __v: 0,
        programId: '693fdb05da98e72cedd4a605',
      },
    ],
    '695e062f8ff0ae30558296fe': [
      {
        _id: '695e062f8ff0ae30558296fe',
        description:
          'To Onboard a participant by taking his consent, SLA and household profile',
        concepts: [''],
        keywords: [
          'Science, Activity Based Learning, STEM Education, STEM Lab, DPDT Switch Car',
        ],
        isDeleted: false,
        recommendedFor: ['Linkage Champion'],
        tasks: [
          {
            _id: '695ef6a4479dcc69fe92b94e',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize and schedule business skills training: Session 1 - Business Idea',
            externalId: 'ONBOARD_1',
            description:
              'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
            sequenceNumber: '1',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.725Z',
            createdAt: '2026-01-08T00:13:24.725Z',
          },
          {
            _id: '695ef6a4479dcc69fe92b952',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize and schedule business skills training: Session 2 - Business finances',
            externalId: 'ONBOARD_2',
            description:
              'Coordinate with service provider to schedule and organize Self Management training session for participant.',
            sequenceNumber: '2',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.750Z',
            createdAt: '2026-01-08T00:13:24.750Z',
          },
        ],
        createdBy: '3077',
        updatedBy: '3077',
        learningResources: [],
        isReusable: true,
        taskSequence: ['ONBOARD_1', 'ONBOARD_2', 'ONBOARD_3'],
        averageRating: 0,
        noOfRatings: 0,
        ratings: {
          '1': 0,
          '2': 0,
          '3': 0,
          '4': 0,
          '5': 0,
        },
        importCount: 0,
        evidences: [],
        isPrivate: false,
        hasSpotlight: false,
        hasStory: false,
        text: [],
        visibility: 'CURRENT',
        visibleToOrganizations: ['brac_gbl'],
        deleted: false,
        title: 'Livelihoods',
        externalId: 'GBL_P01_ONBOARDING',
        categories: [
          {
            _id: '693fb8fcda98e72cedd4a5fd',
            externalId: 'GBL_PATH_ENT',
            name: 'Livelihoods',
          },
        ],
        entityType: 'participant',
        taskCreationForm: '',
        durationInDays: 365,
        metaInformation: {
          testimonials: [],
          goal: 'TEMP',
          rationale: '',
          primaryAudience: '',
          duration: '1 year',
          successIndicators: '',
          risks: '',
          approaches: '',
        },
        status: 'published',
        tenantId: 'brac',
        orgId: 'brac_gbl',
        updatedAt: '2025-12-17T09:44:19.355Z',
        createdAt: '2025-12-17T09:01:53.607Z',
        __v: 0,
        programId: '693fdb05da98e72cedd4a605',
      },
    ],
    '695e07dd094c3e3177f00f40': [
      {
        _id: '695e07dd094c3e3177f00f40',
        description:
          'To Onboard a participant by taking his consent, SLA and household profile',
        concepts: [''],
        keywords: [
          'Science, Activity Based Learning, STEM Education, STEM Lab, DPDT Switch Car',
        ],
        isDeleted: false,
        recommendedFor: ['Linkage Champion'],
        tasks: [
          {
            _id: '695ef6a4479dcc69fe92b94e',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize and schedule business skills training: Session 1 - Business Idea',
            externalId: 'ONBOARD_1',
            description:
              'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
            sequenceNumber: '1',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.725Z',
            createdAt: '2026-01-08T00:13:24.725Z',
          },
          {
            _id: '695ef6a4479dcc69fe92b952',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize and schedule business skills training: Session 2 - Business finances',
            externalId: 'ONBOARD_2',
            description:
              'Coordinate with service provider to schedule and organize Self Management training session for participant.',
            sequenceNumber: '2',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.750Z',
            createdAt: '2026-01-08T00:13:24.750Z',
          },
        ],
        createdBy: '3077',
        updatedBy: '3077',
        learningResources: [],
        isReusable: true,
        taskSequence: ['ONBOARD_1', 'ONBOARD_2', 'ONBOARD_3'],
        averageRating: 0,
        noOfRatings: 0,
        ratings: {
          '1': 0,
          '2': 0,
          '3': 0,
          '4': 0,
          '5': 0,
        },
        importCount: 0,
        evidences: [],
        isPrivate: false,
        hasSpotlight: false,
        hasStory: false,
        text: [],
        visibility: 'CURRENT',
        visibleToOrganizations: ['brac_gbl'],
        deleted: false,
        title: 'Social Protection',
        externalId: 'GBL_P01_ONBOARDING',
        categories: [
          {
            _id: '693fb8fcda98e72cedd4a5fd',
            externalId: 'GBL_PATH_ENT',
            name: 'Livelihoods',
          },
        ],
        entityType: 'participant',
        taskCreationForm: '',
        durationInDays: 365,
        metaInformation: {
          testimonials: [],
          goal: 'TEMP',
          rationale: '',
          primaryAudience: '',
          duration: '1 year',
          successIndicators: '',
          risks: '',
          approaches: '',
        },
        status: 'published',
        tenantId: 'brac',
        orgId: 'brac_gbl',
        updatedAt: '2025-12-17T09:44:19.355Z',
        createdAt: '2025-12-17T09:01:53.607Z',
        __v: 0,
        programId: '693fdb05da98e72cedd4a605',
      },
    ],
    '695e0849094c3e3177f00f4a': [
      {
        _id: '695e0849094c3e3177f00f4a',
        description:
          'To Onboard a participant by taking his consent, SLA and household profile',
        concepts: [''],
        keywords: [
          'Science, Activity Based Learning, STEM Education, STEM Lab, DPDT Switch Car',
        ],
        isDeleted: false,
        recommendedFor: ['Linkage Champion'],
        tasks: [
          {
            _id: '695ef6a4479dcc69fe92b94e',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize and schedule business skills training: Session 1 - Business Idea',
            externalId: 'ONBOARD_1',
            description:
              'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
            sequenceNumber: '1',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.725Z',
            createdAt: '2026-01-08T00:13:24.725Z',
          },
          {
            _id: '695ef6a4479dcc69fe92b952',
            createdBy: '3074',
            updatedBy: '3074',
            isDeleted: false,
            isDeletable: false,
            taskSequence: [],
            children: [],
            visibleIf: [],
            hasSubTasks: false,
            learningResources: [],
            deleted: false,
            type: 'simple',
            name: 'Organize and schedule business skills training: Session 2 - Business finances',
            externalId: 'ONBOARD_2',
            description:
              'Coordinate with service provider to schedule and organize Self Management training session for participant.',
            sequenceNumber: '2',
            tenantId: 'brac',
            orgId: 'brac_gbl',
            metaInformation: {
              hasAParentTask: 'NO',
              parentTaskOperator: '',
              parentTaskValue: '',
              parentTaskId: '',
              isAnExternalTask: '',
              minNoOfSubmissionsRequired: '',
              redirectLink: '',
              buttonLabel: '',
            },
            updatedAt: '2026-01-08T00:13:24.750Z',
            createdAt: '2026-01-08T00:13:24.750Z',
          },
        ],
        createdBy: '3077',
        updatedBy: '3077',
        learningResources: [],
        isReusable: true,
        taskSequence: ['ONBOARD_1', 'ONBOARD_2', 'ONBOARD_3'],
        averageRating: 0,
        noOfRatings: 0,
        ratings: {
          '1': 0,
          '2': 0,
          '3': 0,
          '4': 0,
          '5': 0,
        },
        importCount: 0,
        evidences: [],
        isPrivate: false,
        hasSpotlight: false,
        hasStory: false,
        text: [],
        visibility: 'CURRENT',
        visibleToOrganizations: ['brac_gbl'],
        deleted: false,
        title: 'Financial Inclusion',
        externalId: 'GBL_P01_ONBOARDING',
        categories: [
          {
            _id: '693fb8fcda98e72cedd4a5fd',
            externalId: 'GBL_PATH_ENT',
            name: 'Livelihoods',
          },
        ],
        entityType: 'participant',
        taskCreationForm: '',
        durationInDays: 365,
        metaInformation: {
          testimonials: [],
          goal: 'TEMP',
          rationale: '',
          primaryAudience: '',
          duration: '1 year',
          successIndicators: '',
          risks: '',
          approaches: '',
        },
        status: 'published',
        tenantId: 'brac',
        orgId: 'brac_gbl',
        updatedAt: '2025-12-17T09:44:19.355Z',
        createdAt: '2025-12-17T09:01:53.607Z',
        __v: 0,
        programId: '693fdb05da98e72cedd4a605',
      },
    ],
  },
};
