import { ProjectData } from '../project-player/types/project.types';

export const DUMMY_PROJECT_DATA: ProjectData = {
  _id: 'Onboarding the Participant',
  solutionId: 'sol-community-health-001',
  name: 'Onboarding the Participant',
  description: 'Complete all required steps before enrolling the participant',
  status: 'in-progress',
  progress: 58,
  createdAt: '2024-01-15T08:00:00Z',
  updatedAt: '2024-12-02T10:30:00Z',
  tasks: [
    {
      _id: 'task-onboard-001',
      name: 'Capture Consent',
      description: 'Upload signed consent forms',
      type: 'file',
      status: 'to-do',
      isRequired: true,
      metadata: {
        minFiles: 1,
        category: 'onboarding',
      },
    },

    {
      _id: 'task-onboard-002',
      name: 'Complete Household Profile',
      description: 'Fill in comprehensive household profiling form',
      type: 'observation',
      status: 'to-do',
      isRequired: true,
      observationFormId: 'form-household-profile-v1',
      metadata: {
        category: 'onboarding',
        formType: 'household-profile',
      },
    },

    {
      _id: 'task-onboard-003',
      name: 'Upload SLA Form',
      description: 'Upload signed Service Level Agreement form',
      type: 'file',
      status: 'to-do',
      isRequired: true,
      metadata: {
        minFiles: 1,
        category: 'onboarding',
      },
    },
  ],
};

export const COMPLEX_PROJECT_DATA: ProjectData = {
  _id: 'Employment Pathway',
  solutionId: 'sol-community-health-001',
  name: 'Employment Pathway',
  description:
    'Comprehensive intervention plan for participants seeking formal employment with full support across all pillars',
  status: 'in-progress',
  progress: 58,
  createdAt: '2024-01-15T08:00:00Z',
  updatedAt: '2024-12-02T10:30:00Z',
  tasks: [
    {
      _id: 'task-001',
      name: 'Social Empowerment',
      description: '',
      type: 'project',
      status: 'to-do',
      isRequired: true,
      metadata: {
        minFiles: 1,
        category: 'onboarding',
      },
      children: [
        {
          _id: 'subtask-001',
          name: 'Organize & Schedule training on social empowerment sessions: Session 1 - Emotional Self Awareness',
          description: 
             
            'Coordinate with service provider to schedule and organize Emotional Self Awareness training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-002',
          name: 'Organize & Schedule training on social empowerment sessions: Session 2 - Self Management',
          description:
            
            'Coordinate with service provider to schedule and organize Self Management training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-003',
          name: 'Organize & Schedule training on social empowerment sessions: Session 3 - Relationships',
          description: 'Coordinate with service provider to schedule and organize Relationship training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-004',
          name: 'Organize & Schedule training on social empowerment sessions: Session 4 - Social Awareness',
          description: 'Coordinate with service provider to schedule and organize Social Awareness training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-005',
          name: 'Organize & Schedule training on social empowerment sessions: Session 5 - Communication Skills',
          description: 'Coordinate with service provider to schedule and organize Communication Skills training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-006',
          name: 'Organize & Schedule training on social empowerment sessions: Session 6 - Time Setting',
          description: 'Coordinate with service provider to schedule and organize Time Setting training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-007',
          name: 'Organize & Schedule training on social empowerment sessions: Session 7 - Family Support',
          description: 'Coordinate with service provider to schedule and organize Family Support training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-008',
          name: 'Organize & Schedule training on social empowerment sessions: Session 8 - Positive Family Communication',
          description: 'Coordinate with service provider to schedule and organize Positive Family Communication training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-009',
          name: "Organize & Schedule training on social empowerment sessions: Session 9 - Parent's involvement in schooling",
          description: "Coordinate with service provider to schedule and organize Parent's involvement in schooling training session for participant.",
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-010',
          name: 'Ensure participant attend all Social Empowerment trainings',
          description: 'Track and confirm participant attendance at all scheduled Social Empowerment training sessions.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-011',
          name: 'Create Ad hoc Social Empowerment training when required in the DPG',
          description: 'Create additional Social Empowerment training linkages in the digital platform as needed based on participant requirements.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
      ],
    },
    {
      _id: 'task-002',
      name: 'Livelihoods',
      description: '',
      type: 'project',
      status: 'to-do',
      isRequired: true,
      metadata: {
        minFiles: 1,
        category: 'onboarding',
      },
      children: [
        {
          _id: 'subtask-liv-001',
          name: 'Organize and schedule business skills training: Session 1 - Business idea',
          description: 
          
            'Coordinate with service provider to schedule and organize Business Idea training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-002',
          name: 'Organize and schedule business skills training: Session 2 - Business finances',
          description: 
          
            'Coordinate with service provider to schedule and organize Business Finances training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-003',
          name: 'Organize and schedule business skills training: Session 3 - Marketing and Communications',
          description: 'Coordinate with service provider to schedule and organize Marketing and Communications training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-004',
          name: 'Organize and schedule business skills training: Session 4 - Formalization',
          description: 'Coordinate with service provider to schedule and organize business Formalization training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-005',
          name: 'Generate Business Idea',
          description: 'Work with participant to develop and document their business idea with clear description, target market, and value proposition.',
          type: 'observation',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-006',
          name: 'Support participants to open a bank account (if they don\'t have)',
          description: 'Assist participant in opening a bank account for their business finances if they do not already have one.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-007',
          name: 'Support participants to get a business license',
          description: 'Support participant in obtaining necessary business license and registration.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-008',
          name: 'Support participants to develop and submit a formal business plan/application to relevant service provider (if they don\'t have)',
          description: 'Assist participant in developing a comprehensive business plan and submitting application to relevant funding or support providers.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-009',
          name: 'Approval of business development plan from relevant authorities',
          description: 'Ensure business development plan receives approval from relevant authorities and service providers.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-010',
          name: 'Coordinate asset/funding delivery with opportunity providers, ensure all paperwork is completed',
          description: 'Coordinate with opportunity providers to arrange asset or funding delivery and ensure all required paperwork is properly completed.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-011',
          name: 'Record asset delivery and ensure acknowledgments of receipt are signed and submitted',
          description: 'Document asset delivery, obtain signed acknowledgment of receipt from participant, and submit all required documentation.',
          type: 'observation',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-012',
          name: 'Organize and schedule livelihood specific trainings',
          description: 'Coordinate with service provider to schedule specialized livelihood-specific technical training relevant to participant\'s business sector.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-013',
          name: 'Organize and schedule livelihood specific refresher training',
          description: 'Coordinate with service provider to schedule refresher training sessions for ongoing skill development.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-014',
          name: 'Ensure participants attend all Business skills trainings',
          description: 'Track and confirm participant attendance at all scheduled Business skills training sessions.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-015',
          name: 'Ensure participants attend all livelihood trainings',
          description: 'Track and confirm participant attendance at all scheduled livelihood-specific technical training sessions.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-liv-016',
          name: 'Create Ad hoc Livelihood specific training when required in the DPG',
          description: 'Create additional livelihood-specific training linkages in the digital platform as needed based on participant requirements.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
      ],
    },
    {
      _id: 'task-003',
      name: 'Financial Inclusion',
      description: '',
      type: 'project',
      status: 'to-do',
      isRequired: true,
      metadata: {
        category: 'financial',
      },
      children: [
        {
          _id: 'subtask-005',
          name: 'Organize and schedule Financial inclusion training: Session 1 - Budgeting',
          description: 'Coordinate with service provider to schedule and organize Budgeting training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-006',
          name: 'Organize and schedule Financial inclusion training: Session 2 - Savings',
          description: 'Coordinate with service provider to schedule and organize Savings training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-007',
          name: 'Organize and schedule Financial inclusion training: Session 3 - Credit and Debt Management',
          description: 'Coordinate with service provider to schedule and organize Credit and Debt Management training session for participant.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-008',
          name: 'Ensure participants attend financial inclusion trainings',
          description: 'Track and confirm participant attendance at all scheduled Financial Inclusion training sessions.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
        {
          _id: 'subtask-009',
          name: 'Create Ad hoc financial inclusion training when required in the DPG',
          description: 'Create additional Financial Inclusion training linkages in the digital platform as needed based on participant requirements.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
        },
      ],
    },
    {
      _id: 'task-004',
      name: 'Social Protection',
      description: '',
      type: 'project',
      status: 'to-do',
      isRequired: true,
      metadata: {
        category: 'protection',
        actionRequired: true,
        warningMessage: 'Please review all Social Protection tasks. Tasks requiring evidence are pre-selected. Optional tasks can be added or removed based on participant needs.',
      },
      children: [
        {
          _id: 'subtask-sp-001',
          name: 'Connect Participant to Food Security Intervention',
          description: 'Link participant to Food and Nutrition Social Safety Net Programs available in the area.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
          metadata: {
            evidenceRequired: true,
            badgeText: 'Evidence Required',
            badgeType: 'required',
          },
        },
        {
          _id: 'subtask-sp-002',
          name: 'Create Ad hoc special attention and immediate attention linkages when required in the DPG',
          description: 'Create additional special attention or immediate attention service linkages in the digital platform as urgent needs arise.',
          type: 'file',
          status: 'to-do',
          isRequired: true,
          metadata: {
            evidenceRequired: true,
            badgeText: 'Evidence Required',
            badgeType: 'required',
          },
        },
        {
          _id: 'subtask-sp-003',
          name: 'Special Attention Required (Substance abuse, GBV, mental health, Others)',
          description: 'Identify and connect households with special vulnerabilities (substance abuse, GBV, mental health, disability, or other critical issues) to appropriate specialized support services.',
          type: 'file',
          status: 'to-do',
          isRequired: false,
          metadata: {
            isOptional: true,
            badgeText: 'Optional',
            badgeType: 'optional',
          },
        },
        {
          _id: 'subtask-sp-004',
          name: 'Immediate Response Required',
          description: 'Provide urgent response and support for critical, time-sensitive situations requiring immediate intervention.',
          type: 'file',
          status: 'to-do',
          isRequired: false,
          metadata: {
            isOptional: true,
            badgeText: 'Optional',
            badgeType: 'optional',
          },
        },
      ],
    },
  ],
};

export const PROJECT_PLAYER_CONFIGS = {
  // Edit mode with full permissions
  editMode: {
    mode: 'edit' as const,
    solutionId: 'sol-community-health-001',
    projectId: 'proj-health-assessment-2024',
    maxFileSize: 50,
    baseUrl: 'https://api.example.com',
    accessToken: 'sample-token-abc123',
    language: 'en',
    showAddCustomTaskButton: true, // Show button in edit mode
    profileInfo: {
      id: 123,
      name: 'John Doe',
      email: 'john.doe@brac.org',
      role: 'LC',
      district: 'District-A',
    },
    redirectionLinks: {
      unauthorizedRedirectUrl: '/unauthorized',
    },
  },

  // Preview mode (template view)
  previewMode: {
    mode: 'preview' as const,
    solutionId: 'sol-community-health-001',
    maxFileSize: 10,
    baseUrl: 'https://api.example.com',
    language: 'en',
    showAddCustomTaskButton: true, // Show button in preview mode (can be customized)
  },

  // Read-only mode
  readOnlyMode: {
    mode: 'read-only' as const,
    solutionId: 'sol-community-health-001',
    projectId: 'proj-health-assessment-2024',
    baseUrl: 'https://api.example.com',
    language: 'en',
    showAddCustomTaskButton: false, // Hide button in read-only mode
  },
};
