export default {
  container: {
    px: '$4',
    py: '$6',
    '$md-px': '$6',
  } as const,
  title: {
    fontSize: 24,
    fontWeight: '700',
  } as const,
  cardContainer: {
    bg: '$white',
    borderRadius: '$2xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    p: '$5',
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    width: '100%',
    marginBottom: '$4',
  } as const,
  detailBox: {
    bg: '#F8FAFC',
    borderRadius: '$lg',
    px: '$5',
    py: '$4',
    mb: '$4',
  } as const,
  overdueBadge: {
    bg: '$red50',
    borderColor: '$red300',
    borderWidth: 1,
    px: '$3',
    py: '$1',
    borderRadius: '$full',
  } as const,
  pendingBadge: {
    bg: '$yellow50',
    borderColor: '$yellow200',
    borderWidth: 1,
    px: '$3',
    py: '$1',
    borderRadius: '$full',
  } as const,
  declinedBadge: {
    bg: '$coolGray100',
    borderWidth: 1,
    borderColor: '$coolGray300',
    px: '$3',
    py: '$1',
    borderRadius: '$full',
    alignSelf: 'flex-end',
  } as const,
  requestInfoBtn: {
    borderWidth: 0.5,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  declineBtn: {
    borderWidth: 1,
    borderColor: '$red200',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$red50' } },
  } as const,
  acceptBtn: {
    bg: '$success600',
    px: '$4.5',
    py: '$2',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  summaryBox: {
    bg: '$blue50',
    borderWidth: 1,
    borderColor: '$blue200',
    p: '$4',
    borderRadius: '$xl',
  } as const,
  inputStyle: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    py: '$2',
    '$focus-borderColor': '$primary500',
  } as const,
  textareaStyle: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    h: 85,
    p: '$1',
    '$focus-borderColor': '$primary500',
  } as const,
  modalCancelBtn: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  modalConfirmBtn: {
    bg: '$success600',
    px: '$5',
    py: '$2.5',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  subbox: {
    bg: "$white",
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight200',
  },
  tabsHeader: {
    alignItems: 'center',
    space: 'sm',
  } as const,
  filterContainer: {
    py: '$4' as const,
    px: '$6' as const,
    mb: '$2' as const,
    mt: '$0' as const,
  } as const,
  pendingHeaderBadge: {
    bg: '$warning600',
    px: '$3',
    py: '$0.5',
    borderRadius: '$full',
  } as const,
  overdueHeaderBadge: {
    bg: '$error600',
    px: '$3',
    py: '$0.5',
    borderRadius: '$full',
  } as const,
  cardHeaderRow: {
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    mb: '$4',
  } as const,
  cardTitleCol: {
    space: 'xs',
    flex: 1,
    mr: '$3',
  } as const,
  cardTitleRow: {
    space: 'sm',
    alignItems: 'center',
  } as const,
  cardSubMetaRow: {
    space: 'lg',
    alignItems: 'center',
    flexWrap: 'wrap',
    mt: '$0.5',
  } as const,
  cardSubMetaItem: {
    space: 'xs',
    alignItems: 'center',
  } as const,
  cardDetailRow: {
    alignItems: 'center',
  } as const,
  cardDetailCol: {
    space: 'sm',
    flex: 1,
  } as const,
  footerRow: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '$borderLight200',
    pt: '$3',
    mt: '$1',
  } as const,
  rightActionGroup: {
    space: 'sm',
    alignItems: 'center',
  } as const,
  declineSummaryBox: {
    bg: '$orange50',
    borderWidth: 1,
    borderColor: '$orange100',
    p: '$4',
    borderRadius: '$xl',
  } as const,
  declineSelectTrigger: {
    borderWidth: 1,
    borderColor: '$gray200',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    py: '$2.5',
    justifyContent: 'space-between',
    alignItems: 'center',
    '$focus-borderColor': '$red600',
  } as const,
  declineTextarea: {
    borderWidth: 1,
    borderColor: '$gray200',
    borderRadius: '$lg',
    bg: '$white',
    h: 100,
    p: '$1',
    '$focus-borderColor': '$red600',
  } as const,
  declineCancelBtn: {
    borderWidth: 0.5,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$gray50' } },
  } as const,
  declineConfirmBtn: {
    bg: '$red600',
    px: '$5',
    py: '$2.5',
    borderRadius: '$lg',
    sx: { ':active': { opacity: 0.85 } },
  } as const,
  cardListContainer: {
    width: '100%',
  } as const,
  cardTitleText: {
    fontSize: '$md',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  cardSubMetaText: {
    fontSize: '$xs',
    color: '$textDark600',
  } as const,
  cardDetailBoldText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark800',
  } as const,
  cardDetailText: {
    fontSize: '$sm',
    color: '$textDark700',
  } as const,
  iconAdditionalServicesTitle: {
    size: 19,
    color: '$pillarSocialEmpowerment',
  } as const,
  iconTrainingSessionsTitle: {
    size: 19,
    color: '$blue600',
  } as const,
  iconAssetsTitle: {
    size: 19,
    color: '$success600',
  } as const,
  iconSubMeta: {
    size: 14,
    color: '$textDark500',
  } as const,
  iconDetailBold: {
    size: 15,
    color: '$textDark600',
  } as const,
  iconDetailText: {
    size: 15,
    color: '$textDark500',
  } as const,
  badgeContainer: {
    space: 'xs',
    alignItems: 'flex-end',
  } as const,
  badgeRow: {
    space: 'xs',
    alignItems: 'center',
  } as const,
  badgeIconOverdue: {
    size: 12,
    color: '$red600',
  } as const,
  badgeTextOverdue: {
    fontSize: '$xs',
    color: '$red600',
    fontWeight: '$medium',
  } as const,
  badgeTextPending: {
    fontSize: '$xs',
    color: '$amber600',
    fontWeight: '$bold',
  } as const,
  badgeTextDeclined: {
    color: '$coolGray700',
    fontSize: '$xs',
    fontWeight: '$semibold',
  } as const,
  buttonPressableDetails: {
    sx: { ':active': { opacity: 0.6 } },
  } as const,
  buttonRowMd: {
    space: 'md',
    alignItems: 'center',
  } as const,
  iconDetails: {
    size: 16,
    color: '$textDark800',
  } as const,
  textDetails: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  iconRequestInfo: {
    size: 14,
    color: '$textDark700',
  } as const,
  textRequestInfo: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark700',
  } as const,
  iconDecline: {
    size: 14,
    color: '$red600',
  } as const,
  textDecline: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$red600',
  } as const,
  iconAccept: {
    size: 16,
    color: '$white',
  } as const,
  textAccept: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  modalFooterRow: {
    space: 'sm',
    width: '$full',
    justifyContent: 'flex-end',
    alignItems: 'center',
  } as const,
  modalCancelText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark700',
  } as const,
  modalConfirmRow: {
    space: 'sm',
    alignItems: 'center',
  } as const,
  iconConfirmCheck: {
    size: 16,
    color: '$white',
  } as const,
  modalConfirmText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  modalBodyVStack: {
    space: 'md',
    width: '100%',
    py: '$2',
  } as const,
  summaryTitleRow: {
    space: 'xs',
    alignItems: 'center',
    mb: '$1',
  } as const,
  iconSummaryInfo: {
    size: 16,
    color: '$blue800',
  } as const,
  summaryTitleText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$blue900',
  } as const,
  summaryDetailText: {
    fontSize: '$sm',
    color: '$blue800',
    ml: '$6',
  } as const,
  modalRowFullWidth: {
    space: 'sm',
    width: '100%',
  } as const,
  modalColFlex1: {
    space: 'xs',
    flex: 1,
  } as const,
  modalColFullWidth: {
    space: 'xs',
    width: '100%',
  } as const,
  labelRow: {
    space: 'xs',
    alignItems: 'center',
  } as const,
  labelText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  requiredAsterisk: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$red600',
  } as const,
  modalInputField: {
    fontSize: '$sm',
    color: '$textDark900',
  } as const,
  modalInputPlaceholder: {
    placeholderTextColor: '$textDark400',
    fontSize: '$sm',
    color: '$textDark900',
  } as const,
  iconInputCalendar: {
    size: 16,
    color: '$textDark500',
  } as const,
  iconInputClock: {
    size: 16,
    color: '$textDark500',
  } as const,
  selectTriggerStyle: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    py: '$2.5',
    justifyContent: 'space-between',
    alignItems: 'center',
    '$focus-borderColor': '$primary500',
  } as const,
  iconSelectChevron: {
    size: 18,
    color: '$textDark500',
  } as const,
  summaryVStack: {
    space: 'xs',
  } as const,
  selectIconStyle: {
    mr: '$1',
  } as const,
  declineModalCancelText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  iconDeclineConfirm: {
    size: 15,
    color: '$white',
  } as const,
  declineSummaryTitleText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$orange800',
  } as const,
  declineSummaryValueText: {
    fontSize: '$sm',
    fontWeight: '$medium',
    color: '$orange600',
  } as const,
  declineSelectInputPlaceholder: {
    placeholderTextColor: '$gray300',
    fontSize: '$sm',
    color: '$textDark900',
  } as const,
  iconDeclineChevron: {
    size: 18,
    color: '$gray300',
  } as const,
  declineHintText: {
    fontSize: '$xs',
    color: '$textMutedForeground',

  } as const,
  requestInfoBtnSend: {
    bg: '$red900',
    px: '$5',
    py: '$2.5',
    borderRadius: '$lg',
    sx: { ':active': { opacity: 0.85 } },
  } as const,
  requestInfoSummaryBox: {
    bg: '$blue50',
    borderWidth: 1,
    borderColor: '$blue200',
    p: '$4',
    borderRadius: '$xl',
  } as const,
  requestInfoSummaryTitleText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$blue700',
  } as const,
  requestInfoSummaryValueText: {
    fontSize: '$sm',
    fontWeight: '$medium',
    color: '$blue500',
  } as const,
  requestInfoHintText: {
    fontSize: '$xs',
    color: '$black',
    mt: '$1',
  } as const,
  modalPropsMd: {
    size: 'md',
  } as const,
  modalPropsLg: {
    size: 'lg',
    maxWidth: 680,
  } as const,
  viewDetailsModalProps: {
    size: 'lg',
    maxWidth: 780,
  } as const,
  viewDetailsTitleText: {
    fontSize: '$xl',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  statusBadgePending: {
    bg: '$yellow100',
    borderColor: '$yellow200',
    borderWidth: 1,
    px: '$3',
    py: '$0.5',
    borderRadius: '$full',
  } as const,
  statusTextPending: {
    fontSize: '$xs',
    color: '$yellow500',
    fontWeight: '$bold',
  } as const,
  categoryBadge: {
    bg: '$gray100',
    px: '$3',
    py: '$0.5',
    borderRadius: '$full',
  } as const,
  categoryText: {
    fontSize: '$xs',
    color: '$gray700',
    fontWeight: '$medium',
  } as const,
  btnViewDetailsDecline: {
    borderWidth: 1,
    borderColor: '$red100',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$red50' } },
  } as const,
  btnViewDetailsAccept: {
    bg: '$success600',
    px: '$4.5',
    py: '$2',
    borderRadius: '$lg',
    shadowColor: '$pillarLivelihoods',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$pillarLivelihoods' } },
  } as const,
  btnViewDetailsRequestInfo: {
    borderWidth: 0.5,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$gray50' } },
  } as const,
  textBtnRequestInfo: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  viewDetailsBodyVStack: {
    space: 'lg',
    width: '100%',
    py: '$2',
  } as const,
  sectionHeadingText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
    mb: '$1',
  } as const,
  coachInfoBox: {
    bg: '$bgSidebar',
    borderRadius: '$xl',
  } as const,
  coachInfoVStack: {
    space: 'xs',
  } as const,
  coachInfoVStack1: {
    bg: '$gray100',
    borderRadius: '$lg',
    p: '$3',
  } as const,
  coachInfoRow: {
    space: 'sm',
    mb: '$2',
    alignItems: 'center',
  } as const,
  iconCoachMeta: {
    size: 16,
    color: '$textDark500',
  } as const,
  textCoachName: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark800',
  } as const,
  textHubName: {
    fontSize: '$sm',
    color: '$textDark600',
  } as const,
  iconContact: {
    size: 16,
    color: '$blue600',
  } as const,
  textContact: {
    fontSize: '$sm',
    color: '$blue600',
  } as const,
  gridCardBox: {
    bg: '$bgSidebar',
    p: '$3.5',
    borderRadius: '$lg',
    flex: 1,
  } as const,
  gridCardBoxFullWidth: {
    bg: '$bgSidebar',
    p: '$3.5',
    borderRadius: '$lg',
    width: '100%',
  } as const,
  gridCardLabel: {
    fontSize: '$xs',
    color: '$textDark500',
    mb: '$0.5',
  } as const,
  gridCardValue: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  justificationBox: {
    bg: '$bgSidebar',
    p: '$4',
    borderRadius: '$lg',
  } as const,
  justificationText: {
    fontSize: '$sm',
    color: '$textDark700',
    lineHeight: '$md',
  } as const,
  specialReqBox: {
    bg: '$optionalTaskYellowBg',
    borderWidth: 1,
    borderColor: '$optionalTaskYellowBorder',
    p: '$3.5',
    borderRadius: '$lg',
  } as const,
  iconSpecialReq: {
    size: 18,
    color: '$warning500',
  } as const,
  textSpecialReq: {
    fontSize: '$sm',
    fontWeight: '$medium',
    color: '$warning500',
  } as const,
  headerBadgeText: {
    color: '$white',
    fontSize: '$xs',
    fontWeight: '$bold',
  } as const,
  screenVStack: {
    space: 'md',
    width: '100%',
  } as const,
  tabTextProps: {
    fontSize: '$sm',
  } as const,
  tabButtonContainer: {
    paddingHorizontal: '$5',
  } as const,
  filterInputProps: {
    size: 'sm' as const,
    bg: 'transparent' as const,
    borderColor: '$borderColor' as const,
  } as const,
  requestInfoButtonProps: {
    borderColor: '$borderLight200',
    borderWidth: 0.5,
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  requestInfoIconProps: {
    size: 14,
    color: '$textDark700',
    mr: '$2',
  } as const,
  requestInfoTextProps: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark700',
  } as const,
  declineButtonProps: {
    borderColor: '$red200',
    borderWidth: 1,
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$red50' } },
  } as const,
  declineIconProps: {
    size: 14,
    color: '$red600',
    mr: '$2',
  } as const,
  declineTextProps: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$red600',
  } as const,
  acceptButtonProps: {
    bg: '$success600',
    px: '$4.5',
    py: '$2',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  acceptIconProps: {
    size: 16,
    color: '$white',
    mr: '$2',
  } as const,
  acceptTextProps: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  declineCancelBtnProps: {
    borderColor: '$borderLight200',
    borderRadius: '$lg',
    px: '$4',
    py: '$2.5',
    bg: '$white',
    sx: { ':active': { bg: '$gray50' } },
  } as const,
  declineCancelBtnTextProps: {
    color: '$textPrimary',
    size: 'sm',
    fontWeight: '$medium',
  } as const,
  declineConfirmBtnProps: {
    bg: '$red600',
    borderRadius: '$lg',
    px: '$5',
    py: '$2.5',
    sx: { ':active': { opacity: 0.85 } },
  } as const,
  declineConfirmBtnRowProps: {
    space: 'xs',
    alignItems: 'center',
  } as const,
  declineConfirmBtnIconProps: {
    size: 16,
    color: '$white',
  } as const,
  declineConfirmBtnTextProps: {
    color: '$white',
    size: 'sm',
    fontWeight: '$semibold',
  } as const,
  sectionTitle: {
    fontSize: '$md',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  sectionContainer: {
    position: 'relative',
    marginTop: 35,
    bg: '$backgroundLight50',
    borderColor: '$borderLight200',
    borderWidth: 1,
    borderRadius: '$lg',
    p: '$5',
  } as const,
  sectionRow: {
    space: 'xs',
    alignItems: 'center',
    mb: '$2.5',
    flexDirection: 'row',
    width: '100%',
  } as const,
  openWizard: {
    bg: '$blue50',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: '$blue100',
    py: '$3',
    px: '$6',
    alignItems: 'center',
    justifyContent: 'space-between',
    mt: '$3',
    mb: '$0',
    mx: '-$6',
    flexDirection: 'row',
    width: 'auto',
  } as const,
  footer: {
    space: 'sm',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  } as const,
  cancelButton: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  confirmButton: {
    bg: '$success600',
    px: '$5',
    py: '$2.5',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  scheduleButton: {
    bg: '$success600',
    px: '$5',
    py: '$2.5',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  // Keep the other modal header styles we need
  acceptScheduleHeaderTitleRow: {
    space: 'sm',
    alignItems: 'center',
  } as const,
  acceptScheduleBadge: {
    px: '$2.5',
    py: '$0.5',
    borderWidth: 1,
    borderColor: '$blue600',
    borderRadius: '$full',
    bg: '$blue50',
  } as const,
  acceptScheduleBadgeText: {
    fontSize: '$xs',
    color: '$blue600',
    fontWeight: '$bold',
  } as const,
  acceptScheduleTitleText: {
    fontSize: '$lg',
    fontWeight: '$bold',
    color: '$textDark900',
  } as const,
  acceptScheduleHeaderDescText: {
    fontSize: '$sm',
    color: '$textMutedForeground',
  } as const,
  acceptScheduleCoachNameText: {
    fontWeight: '$bold',
  } as const,
  openWizardTextRow: {
    space: 'xs',
    alignItems: 'center',
    flex: 1,
    mr: '$2',
    flexDirection: 'row',
  } as const,
  openWizardLabelText: {
    fontSize: '$xs',
    fontWeight: '$semibold',
    color: '$blue900',
  } as const,
  openWizardValueText: {
    fontSize: '$xs',
    color: '$blue800',
    fontWeight: '$normal',
  } as const,
  openWizardBulletText: {
    fontSize: '$xs',
    color: '$blue400',
    mx: '$1',
  } as const,
  openWizardBtn: {
    borderWidth: 1,
    borderColor: '$blue300',
    borderRadius: '$md',
    px: '$2',
    height: 30,
    bg: '$white',
    sx: { ':active': { bg: '$blue50' } },
  } as const,
  openWizardBtnText: {
    fontSize: '$xs',
    color: '$blue600',
    fontWeight: '$normal',
  } as const,
  sectionIcon: {
    size: 18,
    color: '$primary500',
  } as const,
  sectionHeaderContainer: {
    position: 'absolute',
    top: -30,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
  } as const,
};
export const ACCEPT_AND_SCHEDULE_FORM_SECTION_STYLES = {
  _container: {
    position: 'relative',
    marginTop: 20,
    bg: '$gray50',
    borderColor: '$borderColor',
    borderWidth: 1,
    borderRadius: '$lg',
    p: '$5',
    mb: '$4',
  },
  _header: {
    position: 'absolute',
    top: -55,
    left: -12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  _icon: {
    size: 18,
    color: '#881337',
  },
  _title: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark900',
  },
};