export const participantJourneyStyles = {
  page: {
    flex: 1 as const,
    bg: '$backgroundColor' as const,
  },
  container: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$8' as const,
    '$md-px': '$8' as const,
    '$md-py': '$10' as const,
  },
  content: {
    space: 'xl' as const,
    alignItems: 'stretch' as const,
    width: '$full' as const,
  },
  header: {
    space: 'xs' as const,
    alignItems: 'flex-start' as const,
    width: '$full' as const,
    mb: '$4' as const,
  },
  title: {
    color: '$textDark900' as const,
    fontSize: '$2xl' as const,
    fontWeight: '$bold' as const,
    lineHeight: '$2xl' as const,
    mb: '$1' as const,
  },
  welcome: {
    color: '$textDark600' as const,
    fontSize: '$md' as const,
    fontWeight: '$normal' as const,
    lineHeight: '$sm' as const,
  },
  cardsGrid: {
    flexDirection: 'column' as const,
    '$md-flexDirection': 'row' as const,
    flexWrap: 'nowrap' as const,
    gap: '$4' as const,
    width: '$full' as const,
  },
  cardColumn: {
    width: '$full' as const,
    '$md-flex': 1 as const,
    '$md-minWidth': 0 as const,
  },
  pressableCard: {
    flex: 1 as const,
    width: '$full' as const,
  },
  cardBox: {
    flex: 1 as const,
    '$md-minHeight': 180 as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$xl' as const,
    p: '$5' as const,
  },
  coachCardBox: {
    flex: 1 as const,
    '$md-minHeight': 180 as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$xl' as const,
    p: '$5' as const,
    shadowColor: '$shadowColor' as const,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2 as const,
  },
  cardBoxHighlight: {
    borderColor: '$purple300' as const,
  },
  linkCardContent: {
    space: 'xs' as const,
    alignItems: 'flex-start' as const,
    justifyContent: 'flex-start' as const,
    height: '$full' as const,
  },
  textContainer: {
    space: 'xs' as const,
    width: '$full' as const,
    mt: '$2' as const,
  },
  iconBadge: {
    w: 40 as const,
    h: 40 as const,
    borderRadius: '$full' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  cardTitle: {
    color: '$textDark900' as const,
    fontSize: '$md' as const,
    fontWeight: '$normal' as const,
    lineHeight: '$md' as const,
  },
  cardDescription: {
    color: '$textDark600' as const,
    fontSize: '$md' as const,
    fontWeight: '$normal' as const,
    lineHeight: '$md' as const,
  },
  coachCardContent: {
    justifyContent: 'center' as const,
    flex: 1 as const,
  },
  coachRow: {
    space: 'md' as const,
    alignItems: 'center' as const,
  },
  coachRowFirstName: {
    space: 'md' as const,
    alignItems: 'center' as const,
    mb: '$5' as const,
  },
  coachText: {
    flex: 1 as const,
    space: 'xs' as const,
  },
  coachLabel: {
    color: '$textMuted' as const,
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
    lineHeight: '$md' as const,
    letterSpacing: 0.8 as const,
    textTransform: 'uppercase' as const,
  },
  coachValue: {
    color: '$textDark900' as const,
    fontSize: '$sm' as const,
    fontWeight: '$bold' as const,
    lineHeight: '$sm' as const,
  },
} as const;
