export const loginStyles = {
  languageSelector: {
    mb: '$8',
    rounded: '$lg',
    bg: '$backgroundLight100',
    fontSize: '$sm',
    color: '$textDark800',
    px: '$4',
    py: '$2',
  },
  scrollView: {
    contentContainerStyle: { flexGrow: 1 },
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    p: '$4',
    bg: '$rose50',
  },
  box: {
    bg: '$white',
    p: '$8',
    borderRadius: '$lg',
    shadowColor: '$gray400',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    w: '$full',
    maxWidth: 420,
  },
  vstack: { space: 'lg', alignItems: 'center' },
  imageLogo: { w: '$20', h: '$20', mb: '$4', resizeMode: 'contain' },
  box2: {
    w: '$full',
    h: '$full',
    bg: '$rose600',
    borderRadius: '$md',
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: { fontSize: '$2xl', fontWeight: '$bold', color: '$white' },
  heading: { size: 'sm', color: '$primary500', textAlign: 'center' },
  vstack2: { space: 'xs', alignItems: 'center', mb: '$4' },
  text2: { fontSize: '$sm', fontWeight: '$semibold', color: '$textDark900' },
  text3: { fontSize: '$sm', color: '$textDark400' },
  vstack3: { space: 'xs', w: '$full' },
  text4: { fontSize: '$sm', fontWeight: '$medium', color: '$textDark800' },
  input: {
    variant: 'rounded',
    size: 'md',
    borderWidth: 0,
    borderRadius: '$lg',
    bg: '$backgroundLight100',
  },
  vstack4: { space: 'xs', w: '$full' },
  text5: { fontSize: '$sm', fontWeight: '$medium', color: '$textDark800' },
  hstack: { w: '$full', space: 'sm', alignItems: 'center' },
  errorBox: { w: '$full', bg: '$red50', p: '$3', borderRadius: '$md' },
  errorText: { fontSize: '$sm', color: '$red600' },
  button: { size: 'lg', w: '$full', variant: 'solid', action: 'primary' },
  buttonText: { color: '$white', fontWeight: '$semibold' },
  vstack5: { space: 'xs', mt: '$4', alignItems: 'center' },
  text6: { fontSize: '$xs', color: '$textDark500', textAlign: 'center' },
  text7: { fontSize: '$xs', color: '$textDark500' },
} as const;
