export const sessionsSupportStyles = {
  container: {
    flex: 1,
  },
  pageHeaderCss: {
    zIndex: 10,
    position: 'relative' as const,
  },
  headerTitleHStack: {
    alignItems: 'center',
    space: 'sm',
  },
  headerTitleText: {
    fontSize: '$2xl',
    lineHeight: '$2xl',
    fontWeight: '600',
    color: '$textForeground',
  },
  rightSectionBox: {
    position: 'relative',
    zIndex: 100,
  },
  rightSectionHStack: {
    space: 'md',
    alignItems: 'center',
  },
  createSessionBtn: {
    variant: 'outline' as const,
    bg: '$white',
    borderColor: '$borderColor',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
    gap: '$1.5',
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    sx: {
      _hover: {
        borderColor: 'transparent !important',
      },
      _focus: {
        borderColor: 'transparent !important',
      },
    },
  },
  createSessionBtnText: {
    color: '$textForegroundColor',
    fontWeight: '$medium',
    fontSize: '$sm',
  },
  requestSupportBtn: {
    variant: 'solid' as const,
    bg: '#8B2842',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
  },
  requestSupportBtnText: {
    color: '$white',
    fontWeight: '$medium',
    fontSize: '$sm',
  },
  backdropPressable: {
    position: 'absolute' as any,
    top: -500,
    left: -1000,
    right: -1000,
    bottom: -1000,
    zIndex: 90,
  },
  dropdownBox: {
    position: 'absolute',
    top: '100%',
    right: 0,
    mt: '$2',
    width: 230,
    bg: '$white',
    borderRadius: '$xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    shadowColor: '$shadowColor',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    zIndex: 100,
    overflow: 'hidden',
  },
  dropdownItemPressable: {
    px: '$3.5',
    py: '$3',
    $hover: { bg: '$accent100' },
    $active: { bg: '$primary50' },
  },
  dropdownItemHStack: {
    space: 'sm',
    alignItems: 'flex-start',
  },
  dropdownItemIconBox: {
    mt: '$0.5',
  },
  dropdownItemVStack: {
    space: 'xs',
    flex: 1,
  },
  dropdownItemTitle: {
    fontSize: '$sm',
    fontWeight: '600',
    color: '#1E293B',
  },
  dropdownItemDescription: {
    fontSize: '$xs',
    color: '#64748B',
    lineHeight: '$xs',
  },
  contentContainer: {
    py: '$6',
  },
  contentVStack: {
    space: 'md',
  },
  comingSoonText: {
    fontSize: '$sm',
    color: '$textSecondary',
  },
  headerBadgeBox: {
    bg: '#FEE2E2',
    px: '$2.5',
    py: '$0.5',
    borderRadius: '$full',
  },
  headerBadgeText: {
    fontSize: '$xs',
    fontWeight: '500',
    color: '#8B2842',
  },
  headerSubTitleText: {
    fontSize: '$xl',
    fontWeight: '600',
    color: '$textForeground',
  },
  requestorFilterContainer: {
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderLight200' as const,
    borderRadius: 16,
    p: '$3' as const,
    width: '$full' as const,
    shadowColor: '$black' as const,
    shadowOffset: { width: 0, height: 4 } as const,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    gap: '$2' as const,
  },
  requestorFilterSearch: {},
  requestorFilterRow: {
    height: 1,
    // bg: '$borderLight200' as const,
    width: '$full' as const,
  },
  requestorFilterButton: {
    mt: 0,
    p: '$1 !important',
    bg: 'transparent' as const,
    borderWidth: 0,
    shadowColor: 'transparent' as const,
    elevation: 0,
    width: '$full' as const,
  },
  requestorFilterInput: {
    variant: 'outline' as const,
    size: 'sm' as const,
    borderRadius: '$lg' as const,
    bg: '$white' as const,
    borderColor: '$borderLight300' as const,
    height: '$9' as const,
  },
  requestorFooter: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
    borderTopWidth: 1,
    borderTopColor: '$borderColor',
    paddingTop: '$2' as any,
  },
  requestorFooterText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
    flex: 1,
  },
  requestorFooterOrgText: {
    fontSize: '$xs' as const,
    color: '$textPrimary' as const,
    fontWeight: '$semibold' as const,
    letterSpacing: '$sm',
  },
  requestorFooterProvinceText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
  },
  requestorFooterActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    columnGap: 12,
    rowGap: 12,
  },
  requestorFooterViewDetailsButton: {
    height: 32 as const,
    minHeight: 32 as const,
    paddingLeft: 12 as const,
    paddingRight: 12 as const,
    borderRadius: 10 as const,
    borderWidth: 1 as const,
    borderColor: '$borderColor' as const,
    bg: 'transparent' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    sx: {
      ':hover': { bg: '$hoverBackground' } as const,
      ':active': { bg: '$hoverBackground' } as const,
    },
  },
  requestorFooterViewDetailsText: {
    fontSize: '$xs !important' as const,
    lineHeight: 14 as const,
    fontWeight: '$semibold' as const,
    color: '$textPrimary' as const,
  },
  requestorFooterAssignButton: {
    height: 32 as const,
    minHeight: 32 as const,
    paddingLeft: 12 as const,
    paddingRight: 12 as const,
    paddingTop: 0 as const,
    paddingBottom: 0 as const,
    borderRadius: 10 as const,
    bg: '$primary500' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: '$1.5' as const,
    sx: {
      ':hover': { opacity: 0.9 } as const,
      ':active': { opacity: 0.9 } as const,
    },
  },
  requestorFooterAssignText: {
    fontSize: '$xs !important' as const,
    lineHeight: 14 as const,
    fontWeight: '$semibold' as const,
    color: '$white !important' as const,
  },
  sessionsFoundText: {
    fontSize: '$sm',
    color: '$textSecondary',
    fontWeight: '$medium',
    marginTop: '$2',
    marginBottom: '$1',
    marginLeft: '$2'
  },
  sessionSupportSubTabBarBox: {
    bg: 'transparent',
  } as const,
  subTabBarBorderWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight100',
    width: '100%',
  } as const,
  subTabButtonContainer: {
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 16,
  } as const,
  // AssignParticipantsModal styles
  assignParticipantsFooterContainer: {
    space: 'md' as const,
    justifyContent: 'flex-end' as const,
    width: '100%' as const,
  },
  assignParticipantsCancelButton: {
    variant: 'outline' as const,
    borderColor: '$borderColor',
    bg: '$white',
    borderRadius: '$lg',
    px: '$5',
    py: '$2',
    flex: 1,
  },
  assignParticipantsCancelButtonText: {
    color: '$textForegroundColor',
    fontSize: '$sm',
    fontWeight: '$semibold',
    textAlign: 'center' as const,
  },
  assignParticipantsConfirmButton: {
    bg: '$primary500',
    borderRadius: '$lg',
    px: '$5',
    py: '$2',
    flex: 1,
  },
  assignParticipantsConfirmButtonText: {
    color: '$white',
    fontSize: '$sm',
    fontWeight: '$semibold',
    textAlign: 'center' as const,
  },
  assignParticipantsModalBodyProps: {
    flex: 1,
    overflow: 'hidden' as const,
  },
  assignParticipantsContentVStack: {
    space: 'md' as const,
    width: '100%' as const,
  },
  assignParticipantsSearchInput: {
    variant: 'outline' as const,
    size: 'md' as const,
    borderColor: '$borderLight300 !important',
    borderRadius: 10,
    bg: '$white',
    alignItems: 'center' as const,
    px: '$3',
    mb: '$2',
    borderWidth: 1,
    sx: {
      _focus: {
        borderColor: '$borderLight300 !important',
        _web: {
          boxShadow: 'none !important',
          borderColor: '$borderLight300 !important',
        },
      },
      _hover: {
        borderColor: '$borderLight300 !important',
      },
    },
  },
  assignParticipantsCountHeaderHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    p: '$3',
    bg: '$gray50 !important',
    borderColor: '$borderColor',
    borderWidth: 1,
    borderRadius: 10,
  },
  assignParticipantsCountLeftHStack: {
    alignItems: 'center' as const,
    space: 'xs' as const,
    fontWeight: '$semibold' as const,
    color: '$black !important',
  },
  assignParticipantsCountLeftText: {
    fontSize: '$sm',
    fontWeight: '$normal' as const,
    color: '$textMuted',
  },
  assignParticipantsCountRightHStack: {
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  assignParticipantsCountRightText: {
    fontSize: '$sm',
    fontWeight: '$normal' as const,
    color: '$primary500',
  },
  assignParticipantsClearAllText: {
    fontSize: '$sm',
    fontWeight: '$normal' as const,
    color: '$textMuted',
  },
  assignParticipantsFlatList: {
    maxHeight: 320,
    width: '100%' as const,
  },
  assignParticipantsFlatListContent: {
    paddingBottom: 16,
  },
  assignParticipantsCard: {
    borderWidth: 1,
    borderRadius: '$xl',
    p: '$3.5',
    bg: '$white',
  },
  assignParticipantsCardStyle: {
    marginBottom: 8,
  },
  assignParticipantsCheckboxBase: {
    width: 20,
    height: 20,
    borderRadius: 9999,
    borderWidth: 2,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  assignParticipantsAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    bg: '$backgroundLight100',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  assignParticipantsAvatarText: {
    fontSize: '$xs',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
  },
  assignParticipantsInfoVStack: {
    flex: 1,
    space: 'xs' as const,
  },
  assignParticipantsNameText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textPrimary',
  },
  assignParticipantsMetaHStack: {
    alignItems: 'center' as const,
    space: 'xs' as const,
  },
  assignParticipantsMetaText: {
    fontSize: '$xs',
    color: '$textSecondary',
  },
  assignParticipantsBadge: {
    borderWidth: 1,
    borderRadius: '$full',
    px: '$2',
    py: '$0.5',
  },
  assignParticipantsBadgeText: {
    fontSize: '$xs',
    fontWeight: '$medium',
  },
  assignParticipantsLoadingContainer: {
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    py: '$10',
    width: '100%' as const,
  },
  assignParticipantsEmptyContainer: {
    py: '$10',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    px: '$6',
  },
  assignParticipantsEmptyText: {
    mt: '$3',
    fontSize: '$sm',
    fontWeight: '$medium',
    color: '$textMutedForeground',
    textAlign: 'center' as const,
  },
  assignParticipantsFooterLoadingContainer: {
    py: '$4',
    alignItems: 'center' as const,
  },
  assignParticipantsDivider: {
    width: 1,
    height: 14,
    bg: '$borderLight300',
    mx: '$3',
  },

  // My Session Card styles
  mySessionCard: {
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: 16,
    px: '$4' as const,
    py: '$4' as const,
    width: '100%' as const,
    shadowColor: '$black' as const,
    shadowOffset: { width: 0, height: 2 } as const,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
    sx: {
      _hover: {
        borderColor: '$primary500 !important',
      },
      _focus: {
        borderColor: '$primary500 !important',
      },
    },
  },
  mySessionsDescriptionText: {
    fontSize: '$sm',
    color: '$textSecondary',
    fontWeight: '$normal' as const,
    paddingBottom: '$3' as const,
  },
  mySessionCardVStack: {
    space: 'md' as const,
    width: '100%' as const,
  },
  mySessionCardHeaderRow: {
    alignItems: 'flex-start' as const,
    justifyContent: 'space-between' as const,
    width: '100%' as const,
    space: 'sm' as const,
  },
  mySessionCardTitle: {
    fontSize: '$md',
    fontWeight: '700' as const,
    color: '$textPrimary',
    lineHeight: '$md',
    flexShrink: 1,
  },
  mySessionCardMetaRow: {
    flexWrap: 'wrap' as const,
    alignItems: 'center' as const,
    gap: '$4' as const,
  },
  mySessionCardMetaItem: {
    alignItems: 'center' as const,
    space: 'xs' as const,
  },
  mySessionCardMetaText: {
    fontSize: '$xs',
    color: '$textSecondary',
  },
  mySessionCardFooter: {
    borderTopWidth: 1,
    borderTopColor: '$borderLight100',
    paddingTop: '$3' as any,
    justifyContent: 'flex-end' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  mySessionCardAssignBtn: {
    borderColor: '$borderColor',
    bg: '$white',
    borderRadius: 10,
    borderWidth: 1,
    height: 32,
    minHeight: 32,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
    paddingBottom: 0,
  },
  mySessionCardAssignBtnText: {
    color: '$textPrimary',
    fontSize: '$xs !important',
    fontWeight: '$normal',
    lineHeight: 12,
  },
  mySessionCardManageBtn: {
    bg: '$primary500',
    borderRadius: 10,
    height: 32,
    minHeight: 32,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 0,
    paddingBottom: 0,
  },
  mySessionCardManageBtnText: {
    color: '$white',
    fontSize: '$xs !important',
    fontWeight: '$normal',
    lineHeight: 12,
  },
  mySessionCardStatusBadgeText: {
    fontSize: '$xs !important',
    fontWeight: '$medium !important',
    lineHeight: '12px !important',
    textTransform: 'none' as const,
  },
  // My Sessions list container
  mySessionsListVStack: {
    space: 'md' as const,
    width: '100%' as const,
  },
  // Session Details styles
  detailsScreenRoot: {
    flex: 1,
    bg: '$backgroundLight50',
  },
  detailsNotFoundContainer: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    p: '$4' as const,
  },
  detailsHeaderTitle: {
    fontSize: '$3xl',
    fontWeight: '700' as const,
    color: '$textPrimary',
    mb: '$3',
    mt: '$3',
  },
  detailsHeaderSubtitle: {
    fontSize: '$md',
    color: '$textSecondary',
    fontWeight: '$normal' as const,
  },
  detailsHeaderLeftSection: {
    flexDirection: 'column' as const,
    alignItems: 'flex-start' as const,
    gap: 8,
  },
  detailsHeaderBackButton: {
    px: '$4 !important',
    py: '$2 !important',
    gap: 8,
    sx: {
      _hover: {
        bg: '$primary100 !important',
        _text: {
          color: '$black !important',
        },
        _icon: {
          color: '$black !important',
        },
      },
    },
  },
  detailsMainContainer: {
    px: '$4',
    py: '$6',
    '$md-px': '$6',
    alignSelf: 'center' as const,
    width: '100%' as const,
    maxWidth: 1200,
  },
  detailsLayoutWrapper: {
    width: '100%' as const,
    justifyContent: 'center' as const,
    alignItems: 'flex-start' as const,
    gap: 24,
  },
  detailsRightCol: {
    flex: 1,
    space: 'md' as const,
    width: '100%' as const,
  },
  detailsLeftCol: {
    width: '100%' as const,
    '$md-width': 360,
    space: 'md' as const,
  },
  detailsContentCard: {
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: 16,
    p: '$6',
    shadowColor: '$shadowColor',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    '$web-boxShadow': '0px 1px 3px rgba(0, 0, 0, 0.1)' as const,
  },
  detailsCardHeader: {
    fontSize: '$md',
    fontWeight: '700' as const,
    color: '$textPrimary',
    mb: '$4',
  },
  detailsCardBodyText: {
    fontSize: '$sm',
    color: '$textSecondary',
    lineHeight: '$md',
  },
  detailsLearningObjectiveItem: {
    alignItems: 'flex-start' as const,
    space: 'sm' as const,
    mb: '$2',
  },
  detailsLearningObjectiveBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    mt: 8,
  },
  detailsLearningObjectiveText: {
    fontSize: '$sm',
    color: '$textPrimary',
    flex: 1,
  },
  detailsAssignBox: {
    bg: '#ece6e6ff',
    borderColor: '#e6c1caff',
    borderWidth: 1,
    borderRadius: '$xl',
    p: '$6',
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: '$6',
    shadowColor: '$shadowColor',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    '$web-boxShadow': '0px 1px 3px rgba(0, 0, 0, 0.1)' as const,
  },
  detailsAssignTextWrapper: {
    flex: 1,
    minWidth: 240,
    space: 'xs' as const,
  },
  detailsAssignHeaderHStack: {
    alignItems: 'center' as const,
    space: 'xs' as const,
    gap: '$3',
  },
  detailsAssignIconProps: {
    size: 20,
    color: '#8B2842',
  },
  detailsAssignTitle: {
    fontSize: '$md',
    fontWeight: '700' as const,
    color: '$textPrimary',
  },
  detailsAssignSubtitle: {
    fontSize: '$md',
    color: '$textSecondary',
    py: '$2',
  },
  detailsAssignButton: {
    bg: '$primary500',
    borderRadius: '$xl',
    px: '$3',
    py: '$1.5',
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: '$2',
  },
  detailsAssignIconProps1: {
    size: 18,
    color: '#fff',
  },
  detailsAssignButtonText: {
    color: '$white',
    fontSize: '$sm',
    fontWeight: '$semibold',
  },
  detailsInfoCard: {
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: 16,
    p: '$6',
    space: 'lg' as const,
    shadowColor: '$shadowColor',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    '$web-boxShadow': '0px 1px 3px rgba(0, 0, 0, 0.1)' as const,
  },
  detailsInfoItem: {
    alignItems: 'flex-start' as const,
    space: 'md' as const,
    mb: '$2',
  },
  detailsIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 10,
    bg: '$primary100',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  detailsIconProps: {
    size: 20,
    color: '#8B2842',
  },
  detailsItemLabel: {
    fontSize: '$xs',
    color: '$textMuted',
    fontWeight: '$medium' as const,
    letterSpacing: '$md',
  },
  detailsItemValue: {
    fontWeight: '600' as const,
    color: '$textPrimary',
    fontSize: '$sm',
    mt: '$0.5',
  },
  detailsDateTimeIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 10,
    bg: '$primary100',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  detailsDateTimeIconProps: {
    size: 20,
    color: '#8B2842',
  },
  detailsDateTimeLabel: {
    fontSize: '$xs',
    color: '$textMuted',
    fontWeight: '$medium' as const,
    letterSpacing: '$md',
  },
  detailsDateValue: {
    fontWeight: '600' as const,
    color: '$textPrimary',
    fontSize: '$sm',
    mt: '$0.5',
  },
  detailsTimeValue: {
    fontWeight: '$normal' as const,
    color: '$textSecondary',
    fontSize: '$xs',
    mt: '$2',
  },
  detailsVirtualLinkText: {
    fontSize: '$sm',
    fontWeight: '600' as const,
    color: '#8B2842',
    textDecorationLine: 'underline' as const,
    mt: '$0.5',
  },
  detailsCapacityText: {
    fontSize: '$sm',
    fontWeight: '600' as const,
    color: '$textPrimary',
    mt: '$0.5',
  },
  detailsSpotsText: {
    fontSize: '$xs',
    fontWeight: '600' as const,
    color: '$green500',
    mt: '$0.5',
  },
  detailsTagsWrapper: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: '$2',
    borderTopWidth: 1,
    borderColor: '$borderColor',
    pt: '$4',
    mt: '$2',
  },
  detailsTagBadge: {
    bg: 'transparent',
    borderColor: '$borderColor',
    borderWidth: 1,
    borderRadius: '$full',
    px: '$3',
    py: '$1',
  },
  detailsTagBadgeText: {
    fontSize: '$xs',
    color: '$textPrimary',
    fontWeight: '$medium' as const,
    sx: {
      _text: {
        color: '$primary500 !important',
      },
    },
  },
  // ConfirmAssignment Modal styles
  confirmAssignmentContainer: {
    space: 'md' as const,
    width: '100%' as const,
  },
  confirmAssignmentSubtitleText: {
    fontSize: '$sm',
    color: '$textSecondary',
    lineHeight: '$md',
    mb: '$4',
  },
  confirmAssignmentSessionBox: {
    bg: '#F8FAFC',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: 16,
    px: '$5',
    py: '$4',
    width: '100%' as const,
    mb: '$5',
  },
  confirmAssignmentSessionName: {
    fontSize: '$md',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
    mb: '$1.5',
  },
  confirmAssignmentSessionMeta: {
    fontSize: '$xs',
    color: '$textMuted',
  },
  confirmAssignmentSectionHeader: {
    fontSize: '$sm',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
    mb: '$3',
  },
  confirmAssignmentParticipantList: {
    width: '100%' as const,
    maxHeight: 200,
    mb: '$6',
  },
  confirmAssignmentParticipantRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    py: '$2',
    width: '100%' as const,
    gap: '$3',
  },
  confirmAssignmentParticipantNameTextContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: '$1.5',
  },
  confirmAssignmentParticipantName: {
    fontSize: '$sm',
    fontWeight: '$medium' as const,
    color: '$textPrimary',
  },
  confirmAssignmentParticipantId: {
    fontSize: '$sm',
    color: '$textMutedForeground',
    fontWeight: '$normal' as const,
  },
  confirmAssignmentFooter: {
    flexDirection: 'row' as const,
    justifyContent: 'flex-end' as const,
    gap: '$3',
    width: '100%' as const,
    mt: '$2',
  },
  confirmAssignmentCancelButton: {
    borderColor: '$borderColor',
    bg: '$white',
    borderRadius: '$lg',
    py: "$2 !important"
  },
  confirmAssignmentCancelButtonText: {
    color: '$textForegroundColor',
    fontSize: '$sm',
    fontWeight: '$semibold',
  },
  confirmAssignmentConfirmButton: {
    bg: '$primary500',
    borderRadius: '$lg',
    py: "$2 !important"
  },
  confirmAssignmentConfirmButtonText: {
    color: '$white',
    fontSize: '$sm',
    fontWeight: '$semibold',
  },
} as const;

export default sessionsSupportStyles;
