export const myGraduationStyles = {
  page: {
    flex: 1 as const,
    bg: '$white' as const,
  },
  topHeaderBar: {
    width: '$full' as const,
    bg: '$white' as const,
    borderBottomWidth: 1 as const,
    borderBottomColor: '$inputBorder' as const,
  },
  headerContainer: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$4' as const,
    '$md-px': '$8' as const,
  },
  headerTitleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  backPressable: {
    borderRadius: '$md' as const,
  },
  backIconBox: {
    p: '$2' as const,
    bg: 'transparent' as const,
    borderRadius: '$md' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  backIconBoxHover: {
    bg: '$primary100' as const,
  },
  title: {
    color: '$textDark900' as const,
    fontSize: '$xl' as const,
    fontWeight: '$bold' as const,
  },
  contentArea: {
    flex: 1 as const,
    width: '$full' as const,
    bg: '$accent100' as const,
  },
  container: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$6' as const,
    '$md-px': '$8' as const,
    '$md-py': '$8' as const,
  },
  content: {
    space: 'md' as const,
    alignItems: 'stretch' as const,
    width: '$full' as const,
  },
  criteriaCard: {
    width: '$full' as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$2xl' as const,
    p: '$6' as const,
    mb: '$2' as const,
  },
  criteriaHeader: {
    mb: '$4' as const,
    space: 'xs' as const,
  },
  criteriaTitle: {
    color: '$textDark900' as const,
    fontSize: '$lg' as const,
    fontWeight: '$bold' as const,
    lineHeight: '$lg' as const,
  },
  criteriaSubtitle: {
    color: '$textMutedForeground' as const,
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
  },
  metricsRow: {
    flexDirection: 'column' as const,
    '$md-flexDirection': 'row' as const,
    gap: '$3' as const,
    width: '$full' as const,
  },
  metricBoxAchieved: {
    flex: 1 as const,
    bg: '$success50' as const,
    borderWidth: 1 as const,
    borderColor: '$success300' as const,
    borderRadius: '$xl' as const,
    py: '$4' as const,
    px: '$3' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  metricValueAchieved: {
    color: '$success600' as const,
    fontSize: '$2xl' as const,
    fontWeight: '$bold' as const,
    lineHeight: '$2xl' as const,
  },
  metricLabelAchieved: {
    color: '$success600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$semibold' as const,
    mt: '$1' as const,
  },
  metricBoxOnTrack: {
    flex: 1 as const,
    bg: '#fffbeb' as const,
    borderWidth: 1 as const,
    borderColor: '#fde68a' as const,
    borderRadius: '$xl' as const,
    py: '$4' as const,
    px: '$3' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  metricValueOnTrack: {
    color: '#ca8a04' as const,
    fontSize: '$2xl' as const,
    fontWeight: '$bold' as const,
    lineHeight: '$2xl' as const,
  },
  metricLabelOnTrack: {
    color: '#ca8a04' as const,
    fontSize: '$sm' as const,
    fontWeight: '$semibold' as const,
    mt: '$1' as const,
  },
  metricBoxAtRisk: {
    flex: 1 as const,
    bg: '$error50' as const,
    borderWidth: 1 as const,
    borderColor: '$error200' as const,
    borderRadius: '$xl' as const,
    py: '$4' as const,
    px: '$3' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  metricValueAtRisk: {
    color: '$error600' as const,
    fontSize: '$2xl' as const,
    fontWeight: '$bold' as const,
    lineHeight: '$2xl' as const,
  },
  metricLabelAtRisk: {
    color: '$error600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$semibold' as const,
    mt: '$1' as const,
  },
  pillarsContainer: {
    space: 'md' as const,
    width: '$full' as const,
  },
  pillarCard: {
    width: '$full' as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$2xl' as const,
    overflow: 'hidden' as const,
  },
  pillarHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    p: '$5' as const,
    bg: '$white' as const,
  },
  pillarLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'md' as const,
    flex: 1 as const,
  },
  pillarIconBox: {
    w: 40 as const,
    h: 40 as const,
    borderRadius: '$lg' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  pillarTitleContainer: {
    space: 'xs' as const,
    flex: 1 as const,
  },
  pillarTitle: {
    color: '$textDark900' as const,
    fontSize: '$md' as const,
    fontWeight: '$bold' as const,
  },
  pillarSubtitle: {
    color: '$textMutedForeground' as const,
    fontSize: '$xs' as const,
  },
  pillarRight: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  pillarBody: {
    p: '$5' as const,
    pt: '$0' as const,
    space: 'md' as const,
  },
  indicatorCard: {
    width: '$full' as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$borderColor' as const,
    borderRadius: '$xl' as const,
    p: '$4' as const,
    space: 'sm' as const,
  },
  indicatorHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    width: '$full' as const,
  },
  indicatorTitleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
    flex: 1 as const,
  },
  indicatorTitle: {
    color: '$textDark900' as const,
    fontSize: '$sm' as const,
    fontWeight: '$bold' as const,
    flex: 1 as const,
  },
  statusBadgeAchieved: {
    bg: '$success50' as const,
    borderWidth: 1 as const,
    borderColor: '$success300' as const,
    px: '$2.5' as const,
    py: '$0.5' as const,
    borderRadius: '$full' as const,
  },
  statusBadgeTextAchieved: {
    color: '$success600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
  },
  statusBadgeOnTrack: {
    bg: '#fffbeb' as const,
    borderWidth: 1 as const,
    borderColor: '#fde68a' as const,
    px: '$2.5' as const,
    py: '$0.5' as const,
    borderRadius: '$full' as const,
  },
  statusBadgeTextOnTrack: {
    color: '#ca8a04' as const,
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
  },
  statusBadgeAtRisk: {
    bg: '$error50' as const,
    borderWidth: 1 as const,
    borderColor: '$error200' as const,
    px: '$2.5' as const,
    py: '$0.5' as const,
    borderRadius: '$full' as const,
  },
  statusBadgeTextAtRisk: {
    color: '$error600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
  },
  indicatorSection: {
    space: 'xs' as const,
    mt: '$1' as const,
  },
  indicatorSectionTitle: {
    color: '$textDark900' as const,
    fontSize: '$xs' as const,
    fontWeight: '$bold' as const,
  },
  indicatorDescription: {
    color: '$textDark600' as const,
    fontSize: '$xs' as const,
    lineHeight: '$sm' as const,
  },
  readinessList: {
    space: 'xs' as const,
    mt: '$1' as const,
  },
  readinessRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    space: 'xs' as const,
  },
  readinessDotGreen: {
    width: 6 as const,
    height: 6 as const,
    borderRadius: '$full' as const,
    bg: '$success600' as const,
    mt: 4 as const,
  },
  readinessDotYellow: {
    width: 6 as const,
    height: 6 as const,
    borderRadius: '$full' as const,
    bg: '#ca8a04' as const,
    mt: 4 as const,
  },
  readinessDotRed: {
    width: 6 as const,
    height: 6 as const,
    borderRadius: '$full' as const,
    bg: '$error600' as const,
    mt: 4 as const,
  },
  readinessText: {
    color: '$textDark600' as const,
    fontSize: '$xs' as const,
    flex: 1 as const,
  },
  logicToggleContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'xs' as const,
    mt: '$2' as const,
    cursor: 'pointer' as const,
  },
  logicToggleText: {
    color: '$textDark600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
  },
  pathwayBadge: {
    alignSelf: 'flex-start' as const,
    bg: '$backgroundLight100' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$md' as const,
    px: '$2' as const,
    py: '$0.5' as const,
    mt: '$2' as const,
  },
  pathwayBadgeText: {
    color: '$textDark600' as const,
    fontSize: 10 as const,
    fontWeight: '$medium' as const,
  },
} as const;
