export const mySessionsStyles = {
  page: {
    flex: 1 as const,
    bg: '$white' as const,
  },
  topHeaderBar: {
    width: '$full' as const,
    bg: '$white' as const,
    borderBottomWidth: 1 as const,
    borderBottomColor: '$inputBorder' as const,
  },
  headerContainer: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$4' as const,
    '$md-px': '$8' as const,
  },
  headerTitleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  backPressable: {
    borderRadius: '$md' as const,
  },
  backIconBox: {
    p: '$2' as const,
    bg: 'transparent' as const,
    borderRadius: '$md' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  backIconBoxHover: {
    bg: '$primary100' as const,
  },
  title: {
    color: '$textDark900' as const,
    fontSize: '$xl' as const,
    fontWeight: '$bold' as const,
  },
  contentArea: {
    flex: 1 as const,
    width: '$full' as const,
    bg: '$accent100' as const,
  },
  container: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$6' as const,
    '$md-px': '$8' as const,
    '$md-py': '$8' as const,
  },
  content: {
    space: 'md' as const,
    alignItems: 'stretch' as const,
    width: '$full' as const,
  },
  subtitle: {
    color: '$textDark600' as const,
    fontSize: '$md' as const,
    fontWeight: '$normal' as const,
    mb: '$6' as const,
  },
  tabRowWrapper: {
    flexDirection: 'column-reverse' as const,
    '$md-flexDirection': 'row' as const,
    alignItems: 'stretch' as const,
    '$md-alignItems': 'center' as const,
    justifyContent: 'space-between' as const,
    gap: '$4' as const,
    width: '$full' as const,
    mb: '$6' as const,
  },
  filterSelectBox: {
    width: '$full' as const,
    '$md-width': 'auto' as const,
    '$md-minWidth': 220 as const,
  },
  tabsContainer: {
    flexDirection: 'row' as const,
    bg: '$backgroundLightGray100' as const,
    p: '$1' as const,
    borderRadius: '$full' as const,
    width: '$full' as const,
    '$md-width': 'auto' as const,
    '$md-alignSelf': 'flex-start' as const,
  },
  tabItem: {
    flex: 1 as const,
    px: '$3' as const,
    py: '$2' as const,
    '$md-px': '$6' as const,
    borderRadius: '$full' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  tabItemActive: {
    bg: '$white' as const,
    shadowColor: '$shadowColor' as const,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1 as const,
  },
  tabItemInactive: {
    bg: 'transparent' as const,
  },
  tabText: {
    fontSize: '$sm' as const,
    fontWeight: '$medium' as const,
  },
  tabTextActive: {
    color: '$textDark900' as const,
    fontWeight: '$semibold' as const,
  },
  tabTextInactive: {
    color: '$textDark600' as const,
    fontWeight: '$medium' as const,
  },
  cardsGrid: {
    flexDirection: 'column' as const,
    '$md-flexDirection': 'row' as const,
    flexWrap: 'wrap' as const,
    gap: '$4' as const,
    width: '$full' as const,
  },
  cardPressable: {
    width: '$full' as const,
    '$md-width': 'calc((100% - 32px) / 3)' as const,
    minHeight: 150 as const,
    borderRadius: '$xl' as const,
  },
  cardBox: {
    width: '$full' as const,
    height: '$full' as const,
    minHeight: 150 as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$xl' as const,
    p: '$4' as const,
    overflow: 'hidden' as const,
    shadowColor: 'transparent' as const,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0 as const,
    '$web-boxShadow': 'none' as const,
    ':hover': {
      borderColor: '$borderLight300' as const,
      shadowColor: '$shadowColor' as const,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 5 as const,
      '$web-boxShadow': '0 4px 20px rgba(0, 0, 0, 0.12)' as const,
    },
  },
  cardHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    space: 'sm' as const,
    mb: '$1' as const,
  },
  cardTitle: {
    color: '$textDark900' as const,
    fontSize: '$md' as const,
    fontWeight: '$bold' as const,
    flex: 1 as const,
    lineHeight: '$md' as const,
  },
  cardSubtitle: {
    color: '$textDark600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
    mt: '$1' as const,
    mb: '$2' as const,
  },

  metaRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: '$2.5' as const,
    maxWidth: '$full' as const,
    overflow: 'hidden' as const,
    mb: '$1.5' as const,
  },
  metaText: {
    color: '$textDark600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$normal' as const,
  },
  locationRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: '$1.5' as const,
    maxWidth: '$full' as const,
    overflow: 'hidden' as const,
    mt: '$1' as const,
    mb: '$1.5' as const,
  },
  locationText: {
    color: '$textDark600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
    flexShrink: 1 as const,
  },
  tagsRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: '$2' as const,
    mt: '$3' as const,
  },
  tagChip: {
    px: '$3' as const,
    py: '$1' as const,
    borderRadius: '$md' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    bg: '$white' as const,
  },
  tagText: {
    color: '$textDark900' as const,
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
  },
  emptyStateContainer: {
    width: '$full' as const,
    py: '$10' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  emptyStateText: {
    color: '$textDark600' as const,
    fontSize: '$md' as const,
  },
} as const;
