import { theme } from '@config/theme';

export const logVisitStyles = {
  container: {
    flex: 1,
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$2xl',
    p: '$6',
  },
  title: {
    fontSize: '$lg',
    fontWeight: '$semibold',
    color: '$textForeground',
  },
  headerContainer: {
    bg: '$white' as const,
    padding: '$4' as const,
    '$md-paddingHorizontal': '$6' as const,
    '$md-paddingVertical': '$4' as const,
    borderBottomWidth: '$1' as const,
    borderBottomColor: '$borderLight300' as const,
  },
  headerContent: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    '$md-alignItems': 'flex-start' as const,
    marginHorizontal: '$0' as const,
    '$md-marginHorizontal': '$24' as const,
    '$md-paddingHorizontal': '$5' as const,
    paddingHorizontal: '$0' as const,
    gap: '$2' as const,
  },
  viewCheckInsButton: {
    variant: 'outline' as const,
    padding: '$3' as const,
    bg: '$accent100' as const,
    borderColor: '$borderLight300' as const,
    borderRadius: '$xl' as const,
    height: '$9' as const,
  },
  viewCheckInsButtonText: {
    color: '$textForeground' as const,
    fontSize: '$sm' as const,
    fontWeight: '$medium' as const,
    display: 'none' as const,
    '$md-display': 'flex' as const,
  },
  cardsContainer: {
    space: 'md' as const,
    paddingVertical: '$4' as const,
    '$md-padding': '$6' as const,
    marginHorizontal: '$0' as const,
    '$md-marginHorizontal': '$24' as const,
    gap: '$4' as const,
    alignItems: 'stretch' as const,
    '$md-alignItems': 'flex-start' as const,
  },
  noteContainer: {
    paddingHorizontal: '$0' as const,
    '$md-paddingHorizontal': '$6' as const,
    marginHorizontal: '$0' as const,
    '$md-marginHorizontal': '$24' as const,
  },
  noteBox: {
    bg: '$accent200' as const,
    borderRadius: '$lg' as const,
    padding: '$4' as const,
    borderWidth: '$1' as const,
    borderColor: '$borderLight300' as const,
    gap: '$2' as const,
  },
} as const;
